using System.Text;

namespace XamlToCSharpGenerator.WPF.Emission;

internal static class RuntimeHelpersEmitter
{
    public static void Emit(GraphEmitter emitter, string? docClassFullName)
    {
        EmitTypeTokenHelper(emitter);
        EmitDependencyPropertyHelper(emitter);
        EmitRoutedEventHelper(emitter);
        EmitStaticResourceHelper(emitter);
        EmitXStaticHelper(emitter, docClassFullName);
        EmitWpfDoubleParserHelper(emitter);
        EmitSetterValueHelper(emitter);
        EmitUnknownMarkupExtensionHelper(emitter);
        EmitTrySetBindingHelper(emitter);
        EmitWpfCommandResolver(emitter, docClassFullName);
    }

    private static void EmitWpfDoubleParserHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private static double __WXSG_ParseWpfDouble(string __raw)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__raw is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.ArgumentNullException(nameof(__raw));");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    var __text = __raw.Trim();");
        sb.AppendLine(i + "    if (global::System.Double.TryParse(__text, global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var __plain))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __plain;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    var __factor = 1D;");
        sb.AppendLine(i + "    if (__text.EndsWith(\"pt\", global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __factor = 96D / 72D;");
        sb.AppendLine(i + "        __text = __text.Substring(0, __text.Length - 2).TrimEnd();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else if (__text.EndsWith(\"in\", global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __factor = 96D;");
        sb.AppendLine(i + "        __text = __text.Substring(0, __text.Length - 2).TrimEnd();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else if (__text.EndsWith(\"cm\", global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __factor = 96D / 2.54D;");
        sb.AppendLine(i + "        __text = __text.Substring(0, __text.Length - 2).TrimEnd();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else if (__text.EndsWith(\"mm\", global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __factor = 96D / 25.4D;");
        sb.AppendLine(i + "        __text = __text.Substring(0, __text.Length - 2).TrimEnd();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else if (__text.EndsWith(\"px\", global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __text = __text.Substring(0, __text.Length - 2).TrimEnd();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    if (global::System.Double.TryParse(__text, global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var __value))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __value * __factor;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    return (double)global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(double)).ConvertFromInvariantString(__raw);");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitTypeTokenHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine();
        sb.AppendLine(i + "private static global::System.Type __WXSG_ResolveTypeToken(string __token)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty type token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    var __colonIndex = __trimmed.IndexOf(':');");
        sb.AppendLine(i + "    if (__colonIndex >= 0 && __colonIndex < __trimmed.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __trimmed = __trimmed.Substring(__colonIndex + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __direct = global::System.Type.GetType(__trimmed, throwOnError: false);");
        sb.AppendLine(i + "    if (__direct is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __direct;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __knownNamespaces = new[]");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        \"System.Windows\",");
        sb.AppendLine(i + "        \"System.Windows.Automation\",");
        sb.AppendLine(i + "        \"System.Windows.Controls\",");
        sb.AppendLine(i + "        \"System.Windows.Controls.Primitives\",");
        sb.AppendLine(i + "        \"System.Windows.Documents\",");
        sb.AppendLine(i + "        \"System.Windows.Input\",");
        sb.AppendLine(i + "        \"System.Windows.Media\",");
        sb.AppendLine(i + "        \"System.Windows.Media.Animation\",");
        sb.AppendLine(i + "        \"System.Windows.Navigation\",");
        sb.AppendLine(i + "        \"System.Windows.Shapes\"");
        sb.AppendLine(i + "    };");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __assemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "    foreach (var __assembly in __assemblies)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __byName = __assembly.GetType(__trimmed, throwOnError: false);");
        sb.AppendLine(i + "        if (__byName is not null)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __byName;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        foreach (var __ns in __knownNamespaces)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __candidate = __assembly.GetType(__ns + \".\" + __trimmed, throwOnError: false);");
        sb.AppendLine(i + "            if (__candidate is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __candidate;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    foreach (var __assembly in __assemblies)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        global::System.Type[] __types;");
        sb.AppendLine(i + "        try");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __assembly.GetTypes();");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        catch (global::System.Reflection.ReflectionTypeLoadException __rtl)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __rtl.Types;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        foreach (var __candidate in __types)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__candidate is null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i);
        sb.AppendLine(i + "            if (string.Equals(__candidate.Name, __trimmed, global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __candidate;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve type token '\" + __token + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitDependencyPropertyHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private static global::System.Windows.DependencyProperty __WXSG_ResolveSetterDependencyProperty(string __token, global::System.Type __styleTargetType)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty dependency property token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    var __lastDot = __trimmed.LastIndexOf('.');");
        sb.AppendLine(i + "    string __ownerToken = null;");
        sb.AppendLine(i + "    string __propertyToken;");
        sb.AppendLine(i + "    if (__lastDot > 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __ownerToken = __trimmed.Substring(0, __lastDot);");
        sb.AppendLine(i + "        __propertyToken = __trimmed.Substring(__lastDot + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __propertyToken = __trimmed;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __ownerPrefixSeparator = __ownerToken is null ? -1 : __ownerToken.IndexOf(':');");
        sb.AppendLine(i + "    if (__ownerPrefixSeparator >= 0 && __ownerPrefixSeparator < __ownerToken.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __ownerToken = __ownerToken.Substring(__ownerPrefixSeparator + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __propertyPrefixSeparator = __propertyToken.IndexOf(':');");
        sb.AppendLine(i + "    if (__propertyPrefixSeparator >= 0 && __propertyPrefixSeparator < __propertyToken.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __propertyToken = __propertyToken.Substring(__propertyPrefixSeparator + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __fieldName = __propertyToken + \"Property\";");
        sb.AppendLine(i);
        sb.AppendLine(i + "    if (!string.IsNullOrWhiteSpace(__ownerToken))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __ownerType = __WXSG_ResolveTypeToken(__ownerToken);");
        sb.AppendLine(i + "        var __ownerField = __ownerType.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "        if (__ownerField?.GetValue(null) is global::System.Windows.DependencyProperty __ownerDp)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __ownerDp;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    for (var __type = __styleTargetType; __type is not null; __type = __type.BaseType)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __field = __type.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "        if (__field?.GetValue(null) is global::System.Windows.DependencyProperty __dp)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __dp;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    foreach (var __assembly in global::System.AppDomain.CurrentDomain.GetAssemblies())");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        global::System.Type[] __types;");
        sb.AppendLine(i + "        try");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __assembly.GetTypes();");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        catch (global::System.Reflection.ReflectionTypeLoadException __rtl)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __rtl.Types;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        foreach (var __candidateType in __types)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__candidateType is null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i);
        sb.AppendLine(i + "            var __candidateField = __candidateType.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "            if (__candidateField?.GetValue(null) is global::System.Windows.DependencyProperty __candidateDp)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __candidateDp;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve dependency property token '\" + __token + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitRoutedEventHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private static global::System.Windows.RoutedEvent __WXSG_ResolveRoutedEvent(global::System.Type __styleTargetType, string __eventName)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var __fieldName = __eventName + \"Event\";");
        sb.AppendLine(i + "    for (var __type = __styleTargetType; __type is not null; __type = __type.BaseType)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __field = __type.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "        if (__field?.GetValue(null) is global::System.Windows.RoutedEvent __re)");
        sb.AppendLine(i + "            return __re;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    foreach (var __assembly in global::System.AppDomain.CurrentDomain.GetAssemblies())");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        global::System.Type[] __types;");
        sb.AppendLine(i + "        try { __types = __assembly.GetTypes(); }");
        sb.AppendLine(i + "        catch (global::System.Reflection.ReflectionTypeLoadException __rtl) { __types = __rtl.Types; }");
        sb.AppendLine(i + "        foreach (var __candidateType in __types)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__candidateType is null) continue;");
        sb.AppendLine(i + "            var __candidateField = __candidateType.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "            if (__candidateField?.GetValue(null) is global::System.Windows.RoutedEvent __re)");
        sb.AppendLine(i + "                return __re;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve routed event '\" + __eventName + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitStaticResourceHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "[global::System.ThreadStatic]");
        sb.AppendLine(i + "private static object __WXSG_CurrentRootResourceScope;");
        sb.AppendLine();
        sb.AppendLine(i + "private static object __WXSG_ResolveStaticResource(object __scope, string __token)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty StaticResource token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    const string __open = \"{StaticResource \";");
        sb.AppendLine(i + "    if (!__trimmed.StartsWith(__open, global::System.StringComparison.Ordinal) || !__trimmed.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Unsupported StaticResource token '\" + __token + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __inner = __trimmed.Substring(__open.Length, __trimmed.Length - __open.Length - 1).Trim();");
        sb.AppendLine(i + "    object __key = __inner;");
        sb.AppendLine(i + "    const string __xStaticOpen = \"{x:Static \";");
        sb.AppendLine(i + "    if (__inner.StartsWith(__xStaticOpen, global::System.StringComparison.Ordinal) && __inner.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __memberToken = __inner.Substring(__xStaticOpen.Length, __inner.Length - __xStaticOpen.Length - 1).Trim();");
        sb.AppendLine(i + "        var __memberDot = __memberToken.LastIndexOf('.');");
        sb.AppendLine(i + "        if (__memberDot > 0 && __memberDot < __memberToken.Length - 1)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __ownerToken = __memberToken.Substring(0, __memberDot);");
        sb.AppendLine(i + "            var __memberName = __memberToken.Substring(__memberDot + 1);");
        sb.AppendLine(i + "            var __ownerType = __WXSG_ResolveTypeToken(__ownerToken);");
        sb.AppendLine(i + "            var __flags = global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "            var __property = __ownerType.GetProperty(__memberName, __flags);");
        sb.AppendLine(i + "            if (__property is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                __key = __property.GetValue(null);");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            else");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                var __field = __ownerType.GetField(__memberName, __flags);");
        sb.AppendLine(i + "                if (__field is not null)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    __key = __field.GetValue(null);");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    object __resource = null;");
        sb.AppendLine(i + "    if (__scope is global::System.Windows.FrameworkElement __frameworkElement)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __resource = __frameworkElement.TryFindResource(__key);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else if (__scope is global::System.Windows.FrameworkContentElement __contentElement)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __resource = __contentElement.TryFindResource(__key);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    if (__resource is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __rootScope = __WXSG_CurrentRootResourceScope;");
        sb.AppendLine(i + "        var __sameAsScope = global::System.Object.ReferenceEquals(__rootScope, __scope);");
        sb.AppendLine(i + "        if (!__sameAsScope && __rootScope is global::System.Windows.FrameworkElement)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __rootFrameworkElement = (global::System.Windows.FrameworkElement)__rootScope;");
        sb.AppendLine(i + "            __resource = __rootFrameworkElement.TryFindResource(__key);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        else if (!__sameAsScope && __rootScope is global::System.Windows.FrameworkContentElement)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __rootContentElement = (global::System.Windows.FrameworkContentElement)__rootScope;");
        sb.AppendLine(i + "            __resource = __rootContentElement.TryFindResource(__key);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    if (__resource is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __app = global::System.Windows.Application.Current;");
        sb.AppendLine(i + "        __resource = __app?.TryFindResource(__key);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    return __resource;");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitXStaticHelper(GraphEmitter emitter, string? docClassFullName)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private static object __WXSG_ResolveXStatic(string __token)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty x:Static token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    const string __open = \"{x:Static \";");
        sb.AppendLine(i + "    if (!__trimmed.StartsWith(__open, global::System.StringComparison.Ordinal) || !__trimmed.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Unsupported x:Static token '\" + __token + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __memberToken = __trimmed.Substring(__open.Length, __trimmed.Length - __open.Length - 1).Trim();");
        sb.AppendLine(i + "    const string __memberPrefix = \"Member=\";");
        sb.AppendLine(i + "    if (__memberToken.StartsWith(__memberPrefix, global::System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __memberToken = __memberToken.Substring(__memberPrefix.Length).Trim();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    // Handle fully-qualified format: \"clr-namespace:XStaticCustomNsSample;assembly=XStaticCustomNsSample:Converters.CollectionsToComposite\"");
        sb.AppendLine(i + "    var __clrNsIdx = __memberToken.IndexOf(\"clr-namespace:\", global::System.StringComparison.Ordinal);");
        sb.AppendLine(i + "    if (__clrNsIdx >= 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        // Extract namespace and assembly info");
        sb.AppendLine(i + "        var __afterPrefix = __memberToken.Substring(__clrNsIdx + 14); // len(\"clr-namespace:\") = 14");
        sb.AppendLine(i + "        var __assemblyIdx = __afterPrefix.IndexOf(';');");
        sb.AppendLine(i + "        var __typeIdx = __afterPrefix.LastIndexOf(':');");
        sb.AppendLine(i + "        if (__typeIdx >= 0 && (__assemblyIdx < 0 || __typeIdx > __assemblyIdx))");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            // Extract CLR namespace; with assembly: \"NS;assembly=ASM:Type.Member\", without: \"NS:Type.Member\"");
        sb.AppendLine(i + "            var __clrNamespace = (__assemblyIdx >= 0 ? __afterPrefix.Substring(0, __assemblyIdx) : __afterPrefix.Substring(0, __typeIdx)).Trim();");
        sb.AppendLine(i + "            var __qualifiedTypeName = __afterPrefix.Substring(__typeIdx + 1).Trim();");
        sb.AppendLine(i + "            var __qualifiedMemberDot = __qualifiedTypeName.LastIndexOf('.');");
        sb.AppendLine(i + "            if (__qualifiedMemberDot > 0 && __qualifiedMemberDot < __qualifiedTypeName.Length - 1)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                var __qualifiedTypeNameShort = __qualifiedTypeName.Substring(0, __qualifiedMemberDot);");
        sb.AppendLine(i + "                var __qualifiedMemberName = __qualifiedTypeName.Substring(__qualifiedMemberDot + 1);");
        sb.AppendLine(i + "                // Try fully-qualified name first: namespace.typename");
        sb.AppendLine(i + "                var __fullyQualifiedTypeName = __clrNamespace + \".\" + __qualifiedTypeNameShort;");
        sb.AppendLine(i + "                var __qualifiedOwnerType = global::System.Type.GetType(__fullyQualifiedTypeName, throwOnError: false);");
        sb.AppendLine(i + "                if (__qualifiedOwnerType is null)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    // Extract assembly name from format: \"XStaticCustomNsSample;assembly=XStaticCustomNsSample:Converters.CollectionsToComposite\"");
        sb.AppendLine(i + "                    var __asmNameStart = __afterPrefix.IndexOf(\"assembly=\");");
        sb.AppendLine(i + "                    string __targetAsmName = null;");
        sb.AppendLine(i + "                    if (__asmNameStart >= 0)");
        sb.AppendLine(i + "                    {");
        sb.AppendLine(i + "                        __asmNameStart += 9; // len(\"assembly=\")");
        sb.AppendLine(i + "                        var __asmNameEnd = __afterPrefix.IndexOf(':', __asmNameStart);");
        sb.AppendLine(i + "                        if (__asmNameEnd > __asmNameStart)");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            __targetAsmName = __afterPrefix.Substring(__asmNameStart, __asmNameEnd - __asmNameStart).Trim();");
        sb.AppendLine(i + "                        }");
        sb.AppendLine(i + "                    }");
        sb.AppendLine(i + "                    // Search loaded assemblies, prioritizing the target assembly");
        sb.AppendLine(i + "                    var __allAssemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "                    if (!string.IsNullOrEmpty(__targetAsmName))");
        sb.AppendLine(i + "                    {");
        sb.AppendLine(i + "                        foreach (var __asm in __allAssemblies)");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            var __asmName = __asm.GetName().Name;");
        sb.AppendLine(i + "                            if (string.Equals(__asmName, __targetAsmName, global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "                            {");
        sb.AppendLine(i + "                                __qualifiedOwnerType = __asm.GetType(__fullyQualifiedTypeName, throwOnError: false);");
        sb.AppendLine(i + "                                if (__qualifiedOwnerType is not null) break;");
        sb.AppendLine(i + "                            }");
        sb.AppendLine(i + "                        }");
        sb.AppendLine(i + "                    }");
        sb.AppendLine(i + "                    if (__qualifiedOwnerType is null)");
        sb.AppendLine(i + "                    {");
        sb.AppendLine(i + "                        foreach (var __asm in __allAssemblies)");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            __qualifiedOwnerType = __asm.GetType(__fullyQualifiedTypeName, throwOnError: false);");
        sb.AppendLine(i + "                            if (__qualifiedOwnerType is not null) break;");
        sb.AppendLine(i + "                        }");
        sb.AppendLine(i + "                    }");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "                if (__qualifiedOwnerType is not null)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    var __qualifiedFlags = global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "                    var __qualifiedProp = __qualifiedOwnerType.GetProperty(__qualifiedMemberName, __qualifiedFlags);");
        sb.AppendLine(i + "                    if (__qualifiedProp is not null) return __qualifiedProp.GetValue(null);");
        sb.AppendLine(i + "                    var __qualifiedField = __qualifiedOwnerType.GetField(__qualifiedMemberName, __qualifiedFlags);");
        sb.AppendLine(i + "                    if (__qualifiedField is not null) return __qualifiedField.GetValue(null);");
        sb.AppendLine(i + "                    var __qualifiedAltMember = __qualifiedMemberName + \"Key\";");
        sb.AppendLine(i + "                    var __qualifiedAltProp = __qualifiedOwnerType.GetProperty(__qualifiedAltMember, __qualifiedFlags);");
        sb.AppendLine(i + "                    if (__qualifiedAltProp is not null) return __qualifiedAltProp.GetValue(null);");
        sb.AppendLine(i + "                    var __qualifiedAltField = __qualifiedOwnerType.GetField(__qualifiedAltMember, __qualifiedFlags);");
        sb.AppendLine(i + "                    if (__qualifiedAltField is not null) return __qualifiedAltField.GetValue(null);");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        // If we processed clr-namespace format but didn't return, error out");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Unable to resolve x:Static member '\" + __memberToken + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    // Fallback: handle XML namespace prefix format (e.g. \"p:Converters.CollectionsToComposite\")");
        sb.AppendLine(i + "    var __colonIdx = __memberToken.IndexOf(':');");
        sb.AppendLine(i + "    var __withoutPrefix = __memberToken;");
        sb.AppendLine(i + "    if (__colonIdx >= 0 && __colonIdx < __memberToken.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __withoutPrefix = __memberToken.Substring(__colonIdx + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    var __memberDot = __withoutPrefix.LastIndexOf('.');");
        sb.AppendLine(i + "    if (__memberDot <= 0 || __memberDot >= __withoutPrefix.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Invalid x:Static member token '\" + __memberToken + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    var __typeName = __withoutPrefix.Substring(0, __memberDot);");
        sb.AppendLine(i + "    var __memberName = __withoutPrefix.Substring(__memberDot + 1);");
        sb.AppendLine(i + "    ");
        sb.AppendLine(i + "    // If we had a namespace prefix, skip standard resolution which finds wrong types");
        sb.AppendLine(i + "    // Otherwise use standard means");
        sb.AppendLine(i + "    var __ownerType = __colonIdx >= 0 ? null : __WXSG_ResolveTypeToken(__typeName);");
        sb.AppendLine(i + "    if (__ownerType is null && __colonIdx >= 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        // Search assemblies with calling assembly first");
        if (!string.IsNullOrEmpty(docClassFullName))
        {
            sb.AppendLine(i + "        var __callingAsm = typeof(" + CodeGenUtilities.QualifyType(docClassFullName) + ").Assembly;");
        }
        else
        {
            sb.AppendLine(i + "        var __callingAsm = global::System.Reflection.Assembly.GetEntryAssembly() ?? typeof(global::System.Windows.Application).Assembly;");
        }
        sb.AppendLine(i + "        var __allAssemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "        global::System.Collections.Generic.List<global::System.Reflection.Assembly> __asmSearchOrder = new();");
        sb.AppendLine(i + "        __asmSearchOrder.Add(__callingAsm);");
        sb.AppendLine(i + "        foreach (var __asm in __allAssemblies)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__asm != __callingAsm) __asmSearchOrder.Add(__asm);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        foreach (var __asm in __asmSearchOrder)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __ownerType = __asm.GetType(__typeName, throwOnError: false);");
        sb.AppendLine(i + "            if (__ownerType is not null) break;");
        sb.AppendLine(i + "            ");
        sb.AppendLine(i + "            global::System.Type[] __types;");
        sb.AppendLine(i + "            try { __types = __asm.GetTypes(); }");
        sb.AppendLine(i + "            catch (global::System.Reflection.ReflectionTypeLoadException __rtle) { __types = __rtle.Types; }");
        sb.AppendLine(i + "            ");
        sb.AppendLine(i + "            foreach (var __t in __types)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                if (__t is not null && __t.Name == __typeName)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    __ownerType = __t;");
        sb.AppendLine(i + "                    break;");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            if (__ownerType is not null) break;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    ");
        sb.AppendLine(i + "    if (__ownerType is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Unable to resolve x:Static type '\" + __typeName + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    ");
        sb.AppendLine(i + "    var __flags = global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "    var __prop = __ownerType.GetProperty(__memberName, __flags);");
        sb.AppendLine(i + "    if (__prop is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __prop.GetValue(null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    var __field = __ownerType.GetField(__memberName, __flags);");
        sb.AppendLine(i + "    if (__field is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __field.GetValue(null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    var __altMemberName = __memberName + \"Key\";");
        sb.AppendLine(i + "    var __altProp = __ownerType.GetProperty(__altMemberName, __flags);");
        sb.AppendLine(i + "    if (__altProp is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __altProp.GetValue(null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    var __altField = __ownerType.GetField(__altMemberName, __flags);");
        sb.AppendLine(i + "    if (__altField is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __altField.GetValue(null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    // Second-pass disambiguation: when multiple types share the same short name (e.g. ResourceKeys),");
        sb.AppendLine(i + "    // pick the type that actually exposes the requested static member.");
        sb.AppendLine(i + "    foreach (var __asm in global::System.AppDomain.CurrentDomain.GetAssemblies())");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        global::System.Type[] __types2;");
        sb.AppendLine(i + "        try { __types2 = __asm.GetTypes(); }");
        sb.AppendLine(i + "        catch (global::System.Reflection.ReflectionTypeLoadException __rtl2) { __types2 = __rtl2.Types; }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "        foreach (var __candidate in __types2)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__candidate is null) continue;");
        sb.AppendLine(i + "            if (!string.Equals(__candidate.Name, __typeName, global::System.StringComparison.Ordinal) &&");
        sb.AppendLine(i + "                !string.Equals(__candidate.FullName, __typeName, global::System.StringComparison.Ordinal) &&");
        sb.AppendLine(i + "                !(__candidate.FullName is not null && __candidate.FullName.EndsWith(\".\" + __typeName, global::System.StringComparison.Ordinal)))");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "            var __candProp = __candidate.GetProperty(__memberName, __flags);");
        sb.AppendLine(i + "            if (__candProp is not null) return __candProp.GetValue(null);");
        sb.AppendLine(i + "            var __candField = __candidate.GetField(__memberName, __flags);");
        sb.AppendLine(i + "            if (__candField is not null) return __candField.GetValue(null);");
        sb.AppendLine(i + "            var __candAltProp = __candidate.GetProperty(__altMemberName, __flags);");
        sb.AppendLine(i + "            if (__candAltProp is not null) return __candAltProp.GetValue(null);");
        sb.AppendLine(i + "            var __candAltField = __candidate.GetField(__altMemberName, __flags);");
        sb.AppendLine(i + "            if (__candAltField is not null) return __candAltField.GetValue(null);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve x:Static member '\" + __memberName + \"' on type '\" + __typeName + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitSetterValueHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private static object __WXSG_ConvertSetterValue(global::System.Windows.DependencyProperty __property, global::System.Type __styleTargetType, object __rawValue)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__property is null || __rawValue is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    if (__rawValue is not string __text)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    var __targetType = __property.PropertyType;");
        sb.AppendLine(i + "    if (__text.StartsWith(\"{StaticResource \", global::System.StringComparison.Ordinal) && __text.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __scope = __WXSG_CurrentRootResourceScope ?? global::System.Windows.Application.Current;");
        sb.AppendLine(i + "        var __resource = __WXSG_ResolveStaticResource(__scope, __text);");
        sb.AppendLine(i + "        if (__resource is not null)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __resource;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    if (__targetType == typeof(string))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __text;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    if (__targetType == typeof(double) || __targetType == typeof(global::System.Nullable<double>))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __WXSG_ParseWpfDouble(__text);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    try");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __converter = global::System.ComponentModel.TypeDescriptor.GetConverter(__targetType);");
        sb.AppendLine(i + "        if (__converter is not null && __converter.CanConvertFrom(typeof(string)))");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __converted = __converter.ConvertFromInvariantString(__text);");
        sb.AppendLine(i + "            if (__converted is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __converted;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    catch");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "    try");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __nonNullable = global::System.Nullable.GetUnderlyingType(__targetType) ?? __targetType;");
        sb.AppendLine(i + "        if (__nonNullable.IsEnum)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return global::System.Enum.Parse(__nonNullable, __text, ignoreCase: true);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "");
        sb.AppendLine(i + "        return global::System.Convert.ChangeType(__text, __nonNullable, global::System.Globalization.CultureInfo.InvariantCulture);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    catch");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        // Fallback: try to locate the DependencyProperty owner field by scanning loaded assemblies.");
        sb.AppendLine(i + "        // Prefer owner types that are assignable from the style target type, if provided.");
        sb.AppendLine(i + "        try");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __assemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "            // First pass: prefer owner types compatible with style target type");
        sb.AppendLine(i + "            if (__styleTargetType is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                foreach (var __asm in __assemblies)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    global::System.Type[] __types2;");
        sb.AppendLine(i + "                    try { __types2 = __asm.GetTypes(); } catch (global::System.Reflection.ReflectionTypeLoadException __rtl2) { __types2 = __rtl2.Types; }");
        sb.AppendLine(i + "                    foreach (var __t2 in __types2)");
        sb.AppendLine(i + "                    {");
        sb.AppendLine(i + "                        if (__t2 is null) continue;");
        sb.AppendLine(i + "                        if (!__t2.IsAssignableFrom(__styleTargetType)) continue;");
        sb.AppendLine(i + "                        var __fields = __t2.GetFields(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "                        foreach (var __f in __fields)");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            object __fv; try { __fv = __f.GetValue(null); } catch { continue; }");
        sb.AppendLine(i + "                            if (!global::System.Object.ReferenceEquals(__fv, __property)) continue;");
        sb.AppendLine(i + "                            var __fn = __f.Name; if (!__fn.EndsWith(\"Property\")) continue;");
        sb.AppendLine(i + "                            var __propName = __fn.Substring(0, __fn.Length - 8);");
        sb.AppendLine(i + "                            var __pi = __t2.GetProperty(__propName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "                            if (__pi is null) continue;");
        sb.AppendLine(i + "                            var __pType = __pi.PropertyType;");
        sb.AppendLine(i + "                            var __nonNullable2 = global::System.Nullable.GetUnderlyingType(__pType) ?? __pType;");
        sb.AppendLine(i + "                            if (__nonNullable2.IsEnum)");
        sb.AppendLine(i + "                            {");
        sb.AppendLine(i + "                                return global::System.Enum.Parse(__nonNullable2, __text, ignoreCase: true);");
        sb.AppendLine(i + "                            }");
        sb.AppendLine(i + "                            try");
        sb.AppendLine(i + "                            {");
        sb.AppendLine(i + "                                var __conv2 = global::System.ComponentModel.TypeDescriptor.GetConverter(__pType);");
        sb.AppendLine(i + "                                if (__conv2 is not null && __conv2.CanConvertFrom(typeof(string)))");
        sb.AppendLine(i + "                                {");
        sb.AppendLine(i + "                                    var __c2 = __conv2.ConvertFromInvariantString(__text);");
        sb.AppendLine(i + "                                    if (__c2 is not null) return __c2;");
        sb.AppendLine(i + "                                }");
        sb.AppendLine(i + "                            } catch { }");
        sb.AppendLine(i + "                        }");
        sb.AppendLine(i + "                    }");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            // Second pass: no style target preference, scan all types");
        sb.AppendLine(i + "            foreach (var __asm in __assemblies)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                global::System.Type[] __types2;");
        sb.AppendLine(i + "                try { __types2 = __asm.GetTypes(); } catch (global::System.Reflection.ReflectionTypeLoadException __rtl2) { __types2 = __rtl2.Types; }");
        sb.AppendLine(i + "                foreach (var __t2 in __types2)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    if (__t2 is null) continue;");
        sb.AppendLine(i + "                    var __fields = __t2.GetFields(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "                    foreach (var __f in __fields)");
        sb.AppendLine(i + "                    {");
        sb.AppendLine(i + "                        object __fv; try { __fv = __f.GetValue(null); } catch { continue; }");
        sb.AppendLine(i + "                        if (!global::System.Object.ReferenceEquals(__fv, __property)) continue;");
        sb.AppendLine(i + "                        var __fn = __f.Name; if (!__fn.EndsWith(\"Property\")) continue;");
        sb.AppendLine(i + "                        var __propName = __fn.Substring(0, __fn.Length - 8);");
        sb.AppendLine(i + "                        var __pi = __t2.GetProperty(__propName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "                        if (__pi is null) continue;");
        sb.AppendLine(i + "                        var __pType = __pi.PropertyType;");
        sb.AppendLine(i + "                        var __nonNullable2 = global::System.Nullable.GetUnderlyingType(__pType) ?? __pType;");
        sb.AppendLine(i + "                        if (__nonNullable2.IsEnum)");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            return global::System.Enum.Parse(__nonNullable2, __text, ignoreCase: true);");
        sb.AppendLine(i + "                        }");
        sb.AppendLine(i + "                        try");
        sb.AppendLine(i + "                        {");
        sb.AppendLine(i + "                            var __conv2 = global::System.ComponentModel.TypeDescriptor.GetConverter(__pType);");
        sb.AppendLine(i + "                            if (__conv2 is not null && __conv2.CanConvertFrom(typeof(string)))");
        sb.AppendLine(i + "                            {");
        sb.AppendLine(i + "                                var __c2 = __conv2.ConvertFromInvariantString(__text);");
        sb.AppendLine(i + "                                if (__c2 is not null) return __c2;");
        sb.AppendLine(i + "                            }");
        sb.AppendLine(i + "                        } catch { }");
        sb.AppendLine(i + "                    }");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        } catch { }");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitUnknownMarkupExtensionHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        // Unknown / custom markup extension runtime resolver.
        // Scans loaded assemblies for XmlnsDefinitionAttribute mapping the given XML namespace
        // URI to CLR namespaces, finds the extension type (<localName>Extension or <localName>),
        // creates an instance with the provided positional constructor argument (if any), applies
        // named property assignments, then calls ProvideValue(null) if the type derives from
        // MarkupExtension.  This mirrors the resolution WPF itself does for custom xmlns prefixes.
        sb.AppendLine(i + "private static object __WXSG_EvaluateUnknownMarkupExtension(");
        sb.AppendLine(i + "    string __xmlNsUri,");
        sb.AppendLine(i + "    string __localName,");
        sb.AppendLine(i + "    string[] __positionalArgs,");
        sb.AppendLine(i + "    string[] __namedArgKeys,");
        sb.AppendLine(i + "    string[] __namedArgValues)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var __typeName = __localName.EndsWith(\"Extension\", global::System.StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine(i + "        ? __localName : __localName + \"Extension\";");
        sb.AppendLine(i + "    var __assemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "    foreach (var __assembly in __assemblies)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __attrs = __assembly.GetCustomAttributes(");
        sb.AppendLine(i + "            typeof(global::System.Windows.Markup.XmlnsDefinitionAttribute), inherit: false);");
        sb.AppendLine(i + "        foreach (global::System.Windows.Markup.XmlnsDefinitionAttribute __def in __attrs)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (!string.Equals(__def.XmlNamespace, __xmlNsUri, global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            var __clrNs = __def.ClrNamespace ?? string.Empty;");
        sb.AppendLine(i + "            var __fullTypeName = string.IsNullOrEmpty(__clrNs)");
        sb.AppendLine(i + "                ? __typeName");
        sb.AppendLine(i + "                : __clrNs + \".\" + __typeName;");
        sb.AppendLine(i + "            var __type = __assembly.GetType(__fullTypeName, throwOnError: false);");
        sb.AppendLine(i + "            if (__type is null)");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            object __instance;");
        sb.AppendLine(i + "            try");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                __instance = __positionalArgs.Length == 0");
        sb.AppendLine(i + "                    ? global::System.Activator.CreateInstance(__type)");
        sb.AppendLine(i + "                    : global::System.Activator.CreateInstance(__type, (object)__positionalArgs[0]);");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            catch { continue; }");
        sb.AppendLine(i + "            for (int __i = 0; __i < __namedArgKeys.Length; __i++)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                var __propInfo = __type.GetProperty(__namedArgKeys[__i]);");
        sb.AppendLine(i + "                __propInfo?.SetValue(__instance, __namedArgValues[__i]);");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            if (__instance is global::System.Windows.Markup.MarkupExtension __ext)");
        sb.AppendLine(i + "                return __ext.ProvideValue(null);");
        sb.AppendLine(i + "            return __instance;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    return null;");
        sb.AppendLine(i + "}");
        sb.AppendLine();
    }

    private static void EmitTrySetBindingHelper(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        // Helper used by the unknown-markup-extension block emitted in EmitPropertyAssignments.
        // Locates the DependencyProperty field for the given property name on the target object's
        // type hierarchy and calls BindingOperations.SetBinding.  A no-op when the property is
        // not a DependencyProperty (e.g. plain CLR property on a non-DO type).
        sb.AppendLine(i + "private static void __WXSG_TrySetBinding(");
        sb.AppendLine(i + "    object __target,");
        sb.AppendLine(i + "    string __propertyName,");
        sb.AppendLine(i + "    global::System.Windows.Data.BindingBase __binding)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (!(__target is global::System.Windows.DependencyObject __depObj))");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    var __dpFieldName = __propertyName + \"Property\";");
        sb.AppendLine(i + "    var __flags = global::System.Reflection.BindingFlags.Public |");
        sb.AppendLine(i + "                  global::System.Reflection.BindingFlags.Static |");
        sb.AppendLine(i + "                  global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "    for (var __t = __depObj.GetType(); __t is not null; __t = __t.BaseType)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __field = __t.GetField(__dpFieldName, __flags);");
        sb.AppendLine(i + "        if (__field?.GetValue(null) is global::System.Windows.DependencyProperty __dp)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            global::System.Windows.Data.BindingOperations.SetBinding(__depObj, __dp, __binding);");
        sb.AppendLine(i + "            return;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
    }

    private static void EmitWpfCommandResolver(GraphEmitter emitter, string? docClassFullName)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        // Resolves a Command attribute string value to an ICommand at runtime.
        // Handles:
        //   1. Short names like "New", "Open" -> ApplicationCommands.New, etc.
        //   2. Namespace-prefixed static references like "Default:MainWindow.CloseAllCommand"
        //      where the prefix is stripped and "Type.Member" is resolved via reflection.
        sb.AppendLine();
        sb.AppendLine(i + "private static global::System.Windows.Input.ICommand __WXSG_ResolveWpfCommand(string __name)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__name))");
        sb.AppendLine(i + "        return null;");
        sb.AppendLine(i + "    var __trimmed = __name.Trim();");
        sb.AppendLine(i + "    // Strip XML namespace prefix (e.g. \"Default:Type.Member\" -> \"Type.Member\")");
        sb.AppendLine(i + "    var __colonIdx = __trimmed.IndexOf(':');");
        sb.AppendLine(i + "    if (__colonIdx >= 0 && __colonIdx < __trimmed.Length - 1)");
        sb.AppendLine(i + "        __trimmed = __trimmed.Substring(__colonIdx + 1);");
        sb.AppendLine(i + "    var __flags = global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "    // Check well-known WPF command classes for a short name (e.g. \"New\" -> ApplicationCommands.New)");
        sb.AppendLine(i + "    var __dot = __trimmed.IndexOf('.');");
        sb.AppendLine(i + "    if (__dot < 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __cmdClasses = new global::System.Type[]");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            typeof(global::System.Windows.Input.ApplicationCommands),");
        sb.AppendLine(i + "            typeof(global::System.Windows.Input.NavigationCommands),");
        sb.AppendLine(i + "            typeof(global::System.Windows.Input.ComponentCommands),");
        sb.AppendLine(i + "            typeof(global::System.Windows.Documents.EditingCommands),");
        sb.AppendLine(i + "            typeof(global::System.Windows.Input.MediaCommands),");
        sb.AppendLine(i + "        };");
        sb.AppendLine(i + "        foreach (var __cls in __cmdClasses)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __prop = __cls.GetProperty(__trimmed, __flags);");
        sb.AppendLine(i + "            if (__prop?.GetValue(null) is global::System.Windows.Input.ICommand __cmd)");
        sb.AppendLine(i + "                return __cmd;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        // \"Type.Member\" format — search loaded assemblies for a matching type");
        sb.AppendLine(i + "        var __typeName = __trimmed.Substring(0, __dot);");
        sb.AppendLine(i + "        var __memberName = __trimmed.Substring(__dot + 1);");
        if (!string.IsNullOrEmpty(docClassFullName))
        {
            sb.AppendLine(i + "        var __callingAsm = typeof(" + CodeGenUtilities.QualifyType(docClassFullName) + ").Assembly;");
        }
        else
        {
            sb.AppendLine(i + "        var __callingAsm = global::System.Reflection.Assembly.GetEntryAssembly() ?? typeof(global::System.Windows.Application).Assembly;");
        }
        sb.AppendLine(i + "        var __allAsms = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "        var __searchOrder = new global::System.Collections.Generic.List<global::System.Reflection.Assembly>();");
        sb.AppendLine(i + "        __searchOrder.Add(__callingAsm);");
        sb.AppendLine(i + "        foreach (var __a in __allAsms) { if (__a != __callingAsm) __searchOrder.Add(__a); }");
        sb.AppendLine(i + "        foreach (var __asm in __searchOrder)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            global::System.Type[] __asmTypes;");
        sb.AppendLine(i + "            try { __asmTypes = __asm.GetTypes(); }");
        sb.AppendLine(i + "            catch (global::System.Reflection.ReflectionTypeLoadException __rtl) { __asmTypes = __rtl.Types; }");
        sb.AppendLine(i + "            foreach (var __t in __asmTypes)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                if (__t is null || __t.Name != __typeName) continue;");
        sb.AppendLine(i + "                var __prop = __t.GetProperty(__memberName, __flags);");
        sb.AppendLine(i + "                if (__prop?.GetValue(null) is global::System.Windows.Input.ICommand __cmd) return __cmd;");
        sb.AppendLine(i + "                var __field = __t.GetField(__memberName, __flags);");
        sb.AppendLine(i + "                if (__field?.GetValue(null) is global::System.Windows.Input.ICommand __cmdF) return __cmdF;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve ICommand '\" + __name + \"'.\");");
        sb.AppendLine(i + "}");
    }
}
