using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Reflection;
using System.Text;
using XamlToCSharpGenerator.Core.Abstractions;
using XamlToCSharpGenerator.Core.Models;
using XamlToCSharpGenerator.Core.Parsing;

namespace XamlToCSharpGenerator.WPF.Emission;

/// <summary>
/// Phase 3 code emitter for WPF XAML.
///
/// Emits pure C# object graph construction (no BAML LoadComponent path).
/// </summary>
public sealed class WpfCodeEmitter : IXamlCodeEmitter
{
    private const string GeneratorVersion = "0.3.0";
    private const string GeneratorName = "XamlToCSharpGenerator.Generator.WPF";
    internal const string WpfFrameworkId = "WPF";

    public (string HintName, string Source) Emit(ResolvedViewModel viewModel)
    {
        var doc = viewModel.Document;
        if (doc.ClassFullName is null)
        {
            return (string.Empty, string.Empty);
        }

        var source = BuildSource(viewModel, doc);
        var hintName = doc.ClassFullName.Replace('.', '_').Replace('+', '_') + ".wpf.g.cs";
        return (hintName, source);
    }

    private static string BuildSource(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var sb = new StringBuilder(1024);
        var ns = doc.ClassNamespace;
        var className = doc.ClassName;
        var modifier = viewModel.ClassModifier;
        var hasNs = !string.IsNullOrEmpty(ns);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by " + GeneratorName + " " + GeneratorVersion);
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable CS0169, CS8618");
        sb.AppendLine();

        if (hasNs)
        {
            sb.AppendLine("namespace " + ns);
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : string.Empty;
        var emitter = new GraphEmitter(viewModel, sb, indent + "    ");

        var classDeclaration = indent + modifier + " partial class " + className;
        var baseTypeName = ResolveBaseTypeName(viewModel, doc);
        if (!string.IsNullOrEmpty(baseTypeName))
        {
            classDeclaration += " : " + baseTypeName;
        }

        sb.AppendLine(classDeclaration);
        sb.AppendLine(indent + "{");

        // If the XAML root is a derived control (root element type != generated class),
        // emit a static ctor that overrides DefaultStyleKey metadata so the derived
        // control automatically picks up the base control's style (no manual ApplyTemplate).
        var rootTypeName = viewModel.RootObject.TypeName;
        if (!IsApplicationDefinition(viewModel) && !string.IsNullOrWhiteSpace(rootTypeName) && !string.IsNullOrWhiteSpace(doc.ClassFullName))
        {
            var normalizedRoot = rootTypeName.Replace("global::", string.Empty);
            // Emit override only for non-system control roots where the XAML root isn't the generated class itself.
            if (!normalizedRoot.StartsWith("System.", StringComparison.Ordinal) &&
                !normalizedRoot.StartsWith("Microsoft.", StringComparison.Ordinal) &&
                !string.Equals(normalizedRoot, doc.ClassFullName, StringComparison.Ordinal))
            {
                sb.AppendLine();
                sb.AppendLine(emitter.MemberIndent + "static " + className + "()");
                sb.AppendLine(emitter.MemberIndent + "{");
                sb.AppendLine(emitter.MemberIndent + "    DefaultStyleKeyProperty.OverrideMetadata(");
                sb.AppendLine(emitter.MemberIndent + "        typeof(" + CodeGenUtilities.QualifyType(doc.ClassFullName) + "),");
                sb.AppendLine(emitter.MemberIndent + "        new global::System.Windows.FrameworkPropertyMetadata(typeof(" + CodeGenUtilities.QualifyType(rootTypeName) + "))");
                sb.AppendLine(emitter.MemberIndent + "    );");
                sb.AppendLine(emitter.MemberIndent + "}");
                sb.AppendLine();
            }
        }

        foreach (var element in viewModel.NamedElements)
        {
            sb.AppendLine(emitter.MemberIndent + "#line " + element.Line.ToString(CultureInfo.InvariantCulture));
            sb.AppendLine(emitter.MemberIndent + "[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Performance\", \"CA1823:AvoidUnusedPrivateFields\")]");
            sb.AppendLine(emitter.MemberIndent + element.FieldModifier + " " + CodeGenUtilities.QualifyType(element.TypeName) + " " + CodeGenUtilities.EscapeIdentifier(element.Name) + ";");
            sb.AppendLine(emitter.MemberIndent + "#line default");
            sb.AppendLine();
        }

        sb.AppendLine(emitter.MemberIndent + "private int __WXSG_HOT_RELOAD__;");
        sb.AppendLine(emitter.MemberIndent + "private bool _contentLoaded;");
        sb.AppendLine();

        EmitInitializeComponent(emitter, viewModel);

        if (IsApplicationDefinition(viewModel))
        {
            var startupWindowType = ResolveStartupWindowType(viewModel, doc);
            if (startupWindowType is not null)
            {
                sb.AppendLine();
                EmitOnStartup(emitter, startupWindowType);
            }

            sb.AppendLine();
            EmitMain(emitter, doc);
        }

        sb.AppendLine(indent + "}");

        if (hasNs)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitInitializeComponent(GraphEmitter emitter, ResolvedViewModel viewModel)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "[global::System.CodeDom.Compiler.GeneratedCode(\"" + GeneratorName + "\", \"" + GeneratorVersion + "\")]");
        sb.AppendLine(i + "public void InitializeComponent()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (_contentLoaded) return;");
        sb.AppendLine(i + "    _contentLoaded = true;");
        sb.AppendLine(i + "    __WXSG_HOT_RELOAD__++;");
        sb.AppendLine(i);
        sb.AppendLine(i + "    // Phase 3: pure C# object-graph construction (no BAML LoadComponent).");
        sb.AppendLine(i + "    __WXSG_BuildObjectGraph();");

        // Runtime fallback: if this XAML-root subclass did not pick up a template via DefaultStyleKey,
        // attempt to find the base control's style at runtime and apply it so templates render
        // even when the implicit theme lookup doesn't resolve automatically.
        var rootType = viewModel.RootObject.TypeName;
        var docClassFullName = viewModel.Document.ClassFullName;
        if (!string.IsNullOrWhiteSpace(rootType) && !string.IsNullOrWhiteSpace(docClassFullName))
        {
            var normalizedRoot = rootType.Replace("global::", string.Empty);
            var normalizedClass = docClassFullName.Replace("global::", string.Empty);
            if (!string.Equals(normalizedRoot, normalizedClass, StringComparison.Ordinal) &&
                !normalizedRoot.StartsWith("System.", StringComparison.Ordinal) &&
                !normalizedRoot.StartsWith("Microsoft.", StringComparison.Ordinal))
            {
                sb.AppendLine(i + "    try");
                sb.AppendLine(i + "    {");
                sb.AppendLine(i + "        var __thisAsControl = this as global::System.Windows.Controls.Control;");
                sb.AppendLine(i + "        if (__thisAsControl != null && __thisAsControl.Template == null)");
                sb.AppendLine(i + "        {");
                sb.AppendLine(i + "            var __fallbackStyle = __thisAsControl.TryFindResource(typeof(" + CodeGenUtilities.QualifyType(rootType) + ")) as global::System.Windows.Style;");
                sb.AppendLine(i + "            if (__fallbackStyle != null)");
                sb.AppendLine(i + "            {");
                sb.AppendLine(i + "                __thisAsControl.Style = __fallbackStyle;");
                sb.AppendLine(i + "                __thisAsControl.ApplyTemplate();");
                sb.AppendLine(i + "            }");
                sb.AppendLine(i + "        }");
                sb.AppendLine(i + "    }");
                sb.AppendLine(i + "    catch { }");
            }
        }
        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "private void __WXSG_BuildObjectGraph()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var __root = this;");
        if (viewModel.NamedElements.Length > 0)
        {
            sb.AppendLine(i + "    if (global::System.Windows.NameScope.GetNameScope(__root) == null)");
            sb.AppendLine(i + "        global::System.Windows.NameScope.SetNameScope(__root, new global::System.Windows.NameScope());");
        }
        sb.AppendLine(i + "    var __previousRootResourceScope = __WXSG_CurrentRootResourceScope;");
        sb.AppendLine(i + "    __WXSG_CurrentRootResourceScope = __root;");
        sb.AppendLine(i + "    var __rootInit = __root as global::System.ComponentModel.ISupportInitialize;");
        sb.AppendLine(i + "    __rootInit?.BeginInit();");
        sb.AppendLine(i + "    try");
        sb.AppendLine(i + "    {");
        emitter.EmitNodeInitialization(viewModel.RootObject, "__root", isRootNode: true, ambientStyleTargetTypeExpression: null);
        sb.AppendLine(i + "        __rootInit?.EndInit();");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    finally");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __WXSG_CurrentRootResourceScope = __previousRootResourceScope;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "internal bool __WXSG_ApplyHotReload(string __filePath, string __xamlText)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    _ = __filePath;");
        sb.AppendLine(i + "    _ = __xamlText;");
        sb.AppendLine(i + "    __WXSG_ResetForHotReload();");
        sb.AppendLine(i + "    __WXSG_HOT_RELOAD__++;");
        sb.AppendLine(i + "    _contentLoaded = true;");
        sb.AppendLine(i + "    __WXSG_BuildObjectGraph();");
        sb.AppendLine(i + "    return true;");
        sb.AppendLine(i + "}");
        sb.AppendLine();

        EmitHotReloadReset(emitter, viewModel);
        RuntimeHelpersEmitter.Emit(emitter, viewModel.Document.ClassFullName);
    }

    private static void EmitHotReloadReset(GraphEmitter emitter, ResolvedViewModel viewModel)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private void __WXSG_ResetForHotReload()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__WXSG_HOT_RELOAD__ <= 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    _contentLoaded = false;");

        if (viewModel.NamedElements.Length > 0)
        {
            sb.AppendLine();
            foreach (var namedElement in viewModel.NamedElements)
            {
                sb.AppendLine(i + "    this." + CodeGenUtilities.EscapeIdentifier(namedElement.Name) + " = null;");
            }
        }

        emitter.EmitHotReloadCollectionCleanup(viewModel.RootObject);

        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "private static void __WXSG_ClearCollectionLike(object __value)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__value is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    if (__value is global::System.Collections.IDictionary __dictionary)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __dictionary.Clear();");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    if (__value is global::System.Collections.IList __list)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __list.Clear();");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    var __clearMethod = __value.GetType().GetMethod(\"Clear\", global::System.Type.EmptyTypes);");
        sb.AppendLine(i + "    if (__clearMethod is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __clearMethod.Invoke(__value, null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
        sb.AppendLine();
        sb.AppendLine(i + "private static object __WXSG_EvaluateMarkupExtension(object __value)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    return __value is global::System.Windows.Markup.MarkupExtension __extension");
        sb.AppendLine(i + "        ? __extension.ProvideValue(null)");
        sb.AppendLine(i + "        : __value;");
        sb.AppendLine(i + "}");
    }

    private static void EmitMain(GraphEmitter emitter, XamlDocumentModel doc)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;
        sb.AppendLine(i + "[global::System.STAThreadAttribute()]");
        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "public static void Main()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var app = new global::" + doc.ClassFullName + "();");
        sb.AppendLine(i + "    app.InitializeComponent();");
        sb.AppendLine(i + "    app.Run();");
        sb.AppendLine(i + "}");
    }

    /// <summary>
    /// Finds the <c>StartupUri</c> property assignment on the Application root node and
    /// derives the startup window's fully-qualified type name using the same filename-to-class
    /// convention WPF itself uses: <c>StartupUri="MainWindow.xaml"</c> →
    /// <c>{AppNamespace}.MainWindow</c>.
    ///
    /// Returns <c>null</c> when <c>StartupUri</c> is not set.
    /// </summary>
    private static string? ResolveStartupWindowType(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        foreach (var assignment in viewModel.RootObject.PropertyAssignments)
        {
            if (!string.Equals(assignment.PropertyName, "StartupUri", StringComparison.Ordinal))
                continue;

            // Value expression is a quoted string like "\"MainWindow.xaml\""
            if (!CodeGenUtilities.TryUnquote(assignment.ValueExpression, out var uriValue))
                uriValue = assignment.ValueExpression.Trim('"');

            if (string.IsNullOrWhiteSpace(uriValue))
                return null;

            // Extract the filename without extension from a potentially path-qualified URI:
            // "MainWindow.xaml"        → "MainWindow"
            // "Views/MainWindow.xaml"  → "MainWindow"
            var fileName = System.IO.Path.GetFileNameWithoutExtension(uriValue.Replace('\\', '/'));
            if (string.IsNullOrWhiteSpace(fileName))
                return null;

            // Prefix with the Application class's namespace (the conventional location for windows).
            var ns = doc.ClassNamespace;
            return string.IsNullOrEmpty(ns) ? fileName : ns + "." + fileName;
        }

        return null;
    }

    private static void EmitOnStartup(GraphEmitter emitter, string startupWindowTypeName)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;
        var qualifiedType = CodeGenUtilities.QualifyType(startupWindowTypeName);
        sb.AppendLine(i + "/// <summary>WPF StartupUri convention: creates and shows the startup window.</summary>");
        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "protected override void OnStartup(global::System.Windows.StartupEventArgs e)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    base.OnStartup(e);");
        sb.AppendLine(i + "    var __startupWindow = new " + qualifiedType + "();");
        sb.AppendLine(i + "    this.MainWindow = __startupWindow;");
        sb.AppendLine(i + "    __startupWindow.Show();");
        sb.AppendLine(i + "}");
    }

    private static bool IsApplicationDefinition(ResolvedViewModel viewModel)
    {
        var typeName = viewModel.RootObject.TypeName.Replace("global::", string.Empty);
        return string.Equals(typeName, "System.Windows.Application", StringComparison.Ordinal);
    }

    private static string? ResolveBaseTypeName(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var rootTypeName = viewModel.RootObject.TypeName;
        if (string.IsNullOrWhiteSpace(rootTypeName))
        {
            return null;
        }

        var normalizedRoot = rootTypeName.Replace("global::", string.Empty);
        if (!string.IsNullOrWhiteSpace(doc.ClassFullName) &&
            string.Equals(normalizedRoot, doc.ClassFullName, StringComparison.Ordinal))
        {
            return null;
        }

        return CodeGenUtilities.QualifyType(rootTypeName);
    }
}
