using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using XamlToCSharpGenerator.Core.Abstractions;
using XamlToCSharpGenerator.Core.Models;
using XamlToCSharpGenerator.Core.Parsing;

namespace XamlToCSharpGenerator.WPF.Emission;

/// <summary>
/// Phase 3 code emitter for WPF XAML.
///
/// Emits pure C# object graph construction (no BAML LoadComponent path).
/// </summary>
public sealed class WpfCodeEmitter : IXamlCodeEmitter
{
    private const string GeneratorVersion = "0.3.0";
    private const string GeneratorName = "XamlToCSharpGenerator.Generator.WPF";
    private const string WpfFrameworkId = "WPF";
    private static readonly MarkupExpressionParser MarkupParser = new();

    public (string HintName, string Source) Emit(ResolvedViewModel viewModel)
    {
        var doc = viewModel.Document;
        if (doc.ClassFullName is null)
        {
            return (string.Empty, string.Empty);
        }

        var source = BuildSource(viewModel, doc);
        var hintName = doc.ClassFullName.Replace('.', '_').Replace('+', '_') + ".wpf.g.cs";
        return (hintName, source);
    }

    private static string BuildSource(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var sb = new StringBuilder(1024);
        var ns = doc.ClassNamespace;
        var className = doc.ClassName;
        var modifier = viewModel.ClassModifier;
        var hasNs = !string.IsNullOrEmpty(ns);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by " + GeneratorName + " " + GeneratorVersion);
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable CS0169, CS8618");
        sb.AppendLine();

        if (hasNs)
        {
            sb.AppendLine("namespace " + ns);
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : string.Empty;
        var emitter = new GraphEmitter(viewModel, sb, indent + "    ");

        var classDeclaration = indent + modifier + " partial class " + className;
        var baseTypeName = ResolveBaseTypeName(viewModel, doc);
        if (!string.IsNullOrEmpty(baseTypeName))
        {
            classDeclaration += " : " + baseTypeName;
        }

        sb.AppendLine(classDeclaration);
        sb.AppendLine(indent + "{");

        foreach (var element in viewModel.NamedElements)
        {
            sb.AppendLine(emitter.MemberIndent + "#line " + element.Line.ToString(CultureInfo.InvariantCulture));
            sb.AppendLine(emitter.MemberIndent + "[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Performance\", \"CA1823:AvoidUnusedPrivateFields\")]");
            sb.AppendLine(emitter.MemberIndent + element.FieldModifier + " " + QualifyType(element.TypeName) + " " + element.Name + ";");
            sb.AppendLine(emitter.MemberIndent + "#line default");
            sb.AppendLine();
        }

        sb.AppendLine(emitter.MemberIndent + "private int __WXSG_HOT_RELOAD__;");
        sb.AppendLine(emitter.MemberIndent + "private bool _contentLoaded;");
        sb.AppendLine();

        EmitInitializeComponent(emitter, viewModel);

        if (IsApplicationDefinition(viewModel))
        {
            var startupWindowType = ResolveStartupWindowType(viewModel, doc);
            if (startupWindowType is not null)
            {
                sb.AppendLine();
                EmitOnStartup(emitter, startupWindowType);
            }

            sb.AppendLine();
            EmitMain(emitter, doc);
        }

        sb.AppendLine(indent + "}");

        if (hasNs)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitInitializeComponent(GraphEmitter emitter, ResolvedViewModel viewModel)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "[global::System.CodeDom.Compiler.GeneratedCode(\"" + GeneratorName + "\", \"" + GeneratorVersion + "\")]");
        sb.AppendLine(i + "public void InitializeComponent()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (_contentLoaded) return;");
        sb.AppendLine(i + "    _contentLoaded = true;");
        sb.AppendLine(i + "    __WXSG_HOT_RELOAD__++;");
        sb.AppendLine(i);
        sb.AppendLine(i + "    // Phase 3: pure C# object-graph construction (no BAML LoadComponent).");
        sb.AppendLine(i + "    __WXSG_BuildObjectGraph();");
        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "private void __WXSG_BuildObjectGraph()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var __root = this;");
        emitter.EmitNodeInitialization(viewModel.RootObject, "__root", isRootNode: true, ambientStyleTargetTypeExpression: null);
        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "internal bool __WXSG_ApplyHotReload(string __filePath, string __xamlText)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    _ = __filePath;");
        sb.AppendLine(i + "    _ = __xamlText;");
        sb.AppendLine(i + "    __WXSG_ResetForHotReload();");
        sb.AppendLine(i + "    __WXSG_HOT_RELOAD__++;");
        sb.AppendLine(i + "    _contentLoaded = true;");
        sb.AppendLine(i + "    __WXSG_BuildObjectGraph();");
        sb.AppendLine(i + "    return true;");
        sb.AppendLine(i + "}");
        sb.AppendLine();

        EmitHotReloadReset(emitter, viewModel);
        EmitRuntimeResolutionHelpers(emitter);
    }

    private static void EmitHotReloadReset(GraphEmitter emitter, ResolvedViewModel viewModel)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine(i + "private void __WXSG_ResetForHotReload()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__WXSG_HOT_RELOAD__ <= 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    _contentLoaded = false;");

        if (viewModel.NamedElements.Length > 0)
        {
            sb.AppendLine();
            foreach (var namedElement in viewModel.NamedElements)
            {
                sb.AppendLine(i + "    this." + namedElement.Name + " = null;");
            }
        }

        emitter.EmitHotReloadCollectionCleanup(viewModel.RootObject);

        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "private static void __WXSG_ClearCollectionLike(object __value)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__value is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    if (__value is global::System.Collections.IDictionary __dictionary)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __dictionary.Clear();");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    if (__value is global::System.Collections.IList __list)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __list.Clear();");
        sb.AppendLine(i + "        return;");
        sb.AppendLine(i + "    }");
        sb.AppendLine();
        sb.AppendLine(i + "    var __clearMethod = __value.GetType().GetMethod(\"Clear\", global::System.Type.EmptyTypes);");
        sb.AppendLine(i + "    if (__clearMethod is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __clearMethod.Invoke(__value, null);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
    }

    private static void EmitRuntimeResolutionHelpers(GraphEmitter emitter)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;

        sb.AppendLine();
        sb.AppendLine(i + "private static global::System.Type __WXSG_ResolveTypeToken(string __token)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty type token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    var __colonIndex = __trimmed.IndexOf(':');");
        sb.AppendLine(i + "    if (__colonIndex >= 0 && __colonIndex < __trimmed.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __trimmed = __trimmed.Substring(__colonIndex + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __direct = global::System.Type.GetType(__trimmed, throwOnError: false);");
        sb.AppendLine(i + "    if (__direct is not null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __direct;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __knownNamespaces = new[]");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        \"System.Windows\",");
        sb.AppendLine(i + "        \"System.Windows.Automation\",");
        sb.AppendLine(i + "        \"System.Windows.Controls\",");
        sb.AppendLine(i + "        \"System.Windows.Controls.Primitives\",");
        sb.AppendLine(i + "        \"System.Windows.Documents\",");
        sb.AppendLine(i + "        \"System.Windows.Input\",");
        sb.AppendLine(i + "        \"System.Windows.Media\",");
        sb.AppendLine(i + "        \"System.Windows.Media.Animation\",");
        sb.AppendLine(i + "        \"System.Windows.Navigation\",");
        sb.AppendLine(i + "        \"System.Windows.Shapes\"");
        sb.AppendLine(i + "    };");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __assemblies = global::System.AppDomain.CurrentDomain.GetAssemblies();");
        sb.AppendLine(i + "    foreach (var __assembly in __assemblies)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __byName = __assembly.GetType(__trimmed, throwOnError: false);");
        sb.AppendLine(i + "        if (__byName is not null)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __byName;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        foreach (var __ns in __knownNamespaces)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __candidate = __assembly.GetType(__ns + \".\" + __trimmed, throwOnError: false);");
        sb.AppendLine(i + "            if (__candidate is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __candidate;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    foreach (var __assembly in __assemblies)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        global::System.Type[] __types;");
        sb.AppendLine(i + "        try");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __assembly.GetTypes();");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "        catch (global::System.Reflection.ReflectionTypeLoadException __rtl)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            __types = __rtl.Types;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        foreach (var __candidate in __types)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            if (__candidate is null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                continue;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i);
        sb.AppendLine(i + "            if (string.Equals(__candidate.Name, __trimmed, global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __candidate;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve type token '\" + __token + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();

        sb.AppendLine(i + "private static global::System.Windows.DependencyProperty __WXSG_ResolveSetterDependencyProperty(string __token, global::System.Type __styleTargetType)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty dependency property token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    var __lastDot = __trimmed.LastIndexOf('.');");
        sb.AppendLine(i + "    string __ownerToken = null;");
        sb.AppendLine(i + "    string __propertyToken;");
        sb.AppendLine(i + "    if (__lastDot > 0)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __ownerToken = __trimmed.Substring(0, __lastDot);");
        sb.AppendLine(i + "        __propertyToken = __trimmed.Substring(__lastDot + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    else");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __propertyToken = __trimmed;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __ownerPrefixSeparator = __ownerToken is null ? -1 : __ownerToken.IndexOf(':');");
        sb.AppendLine(i + "    if (__ownerPrefixSeparator >= 0 && __ownerPrefixSeparator < __ownerToken.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __ownerToken = __ownerToken.Substring(__ownerPrefixSeparator + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __propertyPrefixSeparator = __propertyToken.IndexOf(':');");
        sb.AppendLine(i + "    if (__propertyPrefixSeparator >= 0 && __propertyPrefixSeparator < __propertyToken.Length - 1)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        __propertyToken = __propertyToken.Substring(__propertyPrefixSeparator + 1);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __fieldName = __propertyToken + \"Property\";");
        sb.AppendLine(i);
        sb.AppendLine(i + "    if (!string.IsNullOrWhiteSpace(__ownerToken))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __ownerType = __WXSG_ResolveTypeToken(__ownerToken);");
        sb.AppendLine(i + "        var __ownerField = __ownerType.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "        if (__ownerField?.GetValue(null) is global::System.Windows.DependencyProperty __ownerDp)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __ownerDp;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    for (var __type = __styleTargetType; __type is not null; __type = __type.BaseType)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __field = __type.GetField(__fieldName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy);");
        sb.AppendLine(i + "        if (__field?.GetValue(null) is global::System.Windows.DependencyProperty __dp)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return __dp;");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    throw new global::System.InvalidOperationException(\"Unable to resolve dependency property token '\" + __token + \"'.\");");
        sb.AppendLine(i + "}");
        sb.AppendLine();
        sb.AppendLine(i + "private static object __WXSG_ResolveStaticResource(string __token)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (string.IsNullOrWhiteSpace(__token))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Empty StaticResource token.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __trimmed = __token.Trim();");
        sb.AppendLine(i + "    const string __open = \"{StaticResource \";");
        sb.AppendLine(i + "    if (!__trimmed.StartsWith(__open, global::System.StringComparison.Ordinal) || !__trimmed.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        throw new global::System.InvalidOperationException(\"Unsupported StaticResource token '\" + __token + \"'.\");");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __inner = __trimmed.Substring(__open.Length, __trimmed.Length - __open.Length - 1).Trim();");
        sb.AppendLine(i + "    object __key = __inner;");
        sb.AppendLine(i + "    const string __xStaticOpen = \"{x:Static \";");
        sb.AppendLine(i + "    if (__inner.StartsWith(__xStaticOpen, global::System.StringComparison.Ordinal) && __inner.EndsWith(\"}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __memberToken = __inner.Substring(__xStaticOpen.Length, __inner.Length - __xStaticOpen.Length - 1).Trim();");
        sb.AppendLine(i + "        var __memberDot = __memberToken.LastIndexOf('.');");
        sb.AppendLine(i + "        if (__memberDot > 0 && __memberDot < __memberToken.Length - 1)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __ownerToken = __memberToken.Substring(0, __memberDot);");
        sb.AppendLine(i + "            var __memberName = __memberToken.Substring(__memberDot + 1);");
        sb.AppendLine(i + "            var __ownerType = __WXSG_ResolveTypeToken(__ownerToken);");
        sb.AppendLine(i + "            var __flags = global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.FlattenHierarchy;");
        sb.AppendLine(i + "            var __property = __ownerType.GetProperty(__memberName, __flags);");
        sb.AppendLine(i + "            if (__property is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                __key = __property.GetValue(null);");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "            else");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                var __field = __ownerType.GetField(__memberName, __flags);");
        sb.AppendLine(i + "                if (__field is not null)");
        sb.AppendLine(i + "                {");
        sb.AppendLine(i + "                    __key = __field.GetValue(null);");
        sb.AppendLine(i + "                }");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __app = global::System.Windows.Application.Current;");
        sb.AppendLine(i + "    var __resource = __app?.TryFindResource(__key);");
        sb.AppendLine(i + "    return __resource;");
        sb.AppendLine(i + "}");
        sb.AppendLine();
        sb.AppendLine(i + "private static object __WXSG_ConvertSetterValue(global::System.Windows.DependencyProperty __property, object __rawValue)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    if (__property is null || __rawValue is null)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    if (__rawValue is not string __text)");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    var __targetType = __property.PropertyType;");
        sb.AppendLine(i + "    if (__targetType == typeof(string))");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __text;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    try");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __converter = global::System.ComponentModel.TypeDescriptor.GetConverter(__targetType);");
        sb.AppendLine(i + "        if (__converter is not null && __converter.CanConvertFrom(typeof(string)))");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            var __converted = __converter.ConvertFromInvariantString(__text);");
        sb.AppendLine(i + "            if (__converted is not null)");
        sb.AppendLine(i + "            {");
        sb.AppendLine(i + "                return __converted;");
        sb.AppendLine(i + "            }");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    catch");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i);
        sb.AppendLine(i + "    try");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        var __nonNullable = global::System.Nullable.GetUnderlyingType(__targetType) ?? __targetType;");
        sb.AppendLine(i + "        if (__nonNullable.IsEnum)");
        sb.AppendLine(i + "        {");
        sb.AppendLine(i + "            return global::System.Enum.Parse(__nonNullable, __text, ignoreCase: true);");
        sb.AppendLine(i + "        }");
        sb.AppendLine(i);
        sb.AppendLine(i + "        return global::System.Convert.ChangeType(__text, __nonNullable, global::System.Globalization.CultureInfo.InvariantCulture);");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "    catch");
        sb.AppendLine(i + "    {");
        sb.AppendLine(i + "        return __rawValue;");
        sb.AppendLine(i + "    }");
        sb.AppendLine(i + "}");
    }

    private static void EmitMain(GraphEmitter emitter, XamlDocumentModel doc)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;
        sb.AppendLine(i + "[global::System.STAThreadAttribute()]");
        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "public static void Main()");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    var app = new global::" + doc.ClassFullName + "();");
        sb.AppendLine(i + "    app.InitializeComponent();");
        sb.AppendLine(i + "    app.Run();");
        sb.AppendLine(i + "}");
    }

    /// <summary>
    /// Finds the <c>StartupUri</c> property assignment on the Application root node and
    /// derives the startup window's fully-qualified type name using the same filename-to-class
    /// convention WPF itself uses: <c>StartupUri="MainWindow.xaml"</c> →
    /// <c>{AppNamespace}.MainWindow</c>.
    ///
    /// Returns <c>null</c> when <c>StartupUri</c> is not set.
    /// </summary>
    private static string? ResolveStartupWindowType(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        foreach (var assignment in viewModel.RootObject.PropertyAssignments)
        {
            if (!string.Equals(assignment.PropertyName, "StartupUri", StringComparison.Ordinal))
                continue;

            // Value expression is a quoted string like "\"MainWindow.xaml\""
            if (!TryUnquote(assignment.ValueExpression, out var uriValue))
                uriValue = assignment.ValueExpression.Trim('"');

            if (string.IsNullOrWhiteSpace(uriValue))
                return null;

            // Extract the filename without extension from a potentially path-qualified URI:
            // "MainWindow.xaml"        → "MainWindow"
            // "Views/MainWindow.xaml"  → "MainWindow"
            var fileName = System.IO.Path.GetFileNameWithoutExtension(uriValue.Replace('\\', '/'));
            if (string.IsNullOrWhiteSpace(fileName))
                return null;

            // Prefix with the Application class's namespace (the conventional location for windows).
            var ns = doc.ClassNamespace;
            return string.IsNullOrEmpty(ns) ? fileName : ns + "." + fileName;
        }

        return null;
    }

    private static void EmitOnStartup(GraphEmitter emitter, string startupWindowTypeName)
    {
        var sb = emitter.Builder;
        var i = emitter.MemberIndent;
        var qualifiedType = QualifyType(startupWindowTypeName);
        sb.AppendLine(i + "/// <summary>WPF StartupUri convention: creates and shows the startup window.</summary>");
        sb.AppendLine(i + "[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine(i + "protected override void OnStartup(global::System.Windows.StartupEventArgs e)");
        sb.AppendLine(i + "{");
        sb.AppendLine(i + "    base.OnStartup(e);");
        sb.AppendLine(i + "    var __startupWindow = new " + qualifiedType + "();");
        sb.AppendLine(i + "    this.MainWindow = __startupWindow;");
        sb.AppendLine(i + "    __startupWindow.Show();");
        sb.AppendLine(i + "}");
    }

    private static bool IsApplicationDefinition(ResolvedViewModel viewModel)
    {
        var typeName = viewModel.RootObject.TypeName.Replace("global::", string.Empty);
        return string.Equals(typeName, "System.Windows.Application", StringComparison.Ordinal);
    }

    private static string ConvertLiteralExpression(string valueExpression, string? clrPropertyTypeName)
    {
        if (string.IsNullOrWhiteSpace(clrPropertyTypeName))
        {
            return valueExpression;
        }

        var normalizedType = clrPropertyTypeName.Replace("global::", string.Empty).Trim();
        if (normalizedType.Length == 0)
        {
            return valueExpression;
        }

        if (!TryUnquote(valueExpression, out var literalValue))
        {
            return valueExpression;
        }

        if (normalizedType == "string" || normalizedType == "System.String" || normalizedType == "object" || normalizedType == "System.Object")
        {
            return valueExpression;
        }

        if (literalValue.StartsWith("{StaticResource ", StringComparison.Ordinal) &&
            literalValue.EndsWith("}", StringComparison.Ordinal))
        {
            return "(" + QualifyType(normalizedType) + ")__WXSG_ResolveStaticResource(" + valueExpression + ")";
        }

        if (normalizedType == "Type" || normalizedType == "System.Type")
        {
            return "__WXSG_ResolveTypeToken(" + valueExpression + ")";
        }

        if (normalizedType == "bool" || normalizedType == "System.Boolean")
        {
            return bool.TryParse(literalValue, out var boolValue)
                ? (boolValue ? "true" : "false")
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType == "int" || normalizedType == "System.Int32")
        {
            return int.TryParse(literalValue, NumberStyles.Integer, CultureInfo.InvariantCulture, out var intValue)
                ? intValue.ToString(CultureInfo.InvariantCulture)
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType == "long" || normalizedType == "System.Int64")
        {
            return long.TryParse(literalValue, NumberStyles.Integer, CultureInfo.InvariantCulture, out var longValue)
                ? longValue.ToString(CultureInfo.InvariantCulture) + "L"
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType == "double" || normalizedType == "System.Double")
        {
            return double.TryParse(literalValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var doubleValue)
                ? doubleValue.ToString("R", CultureInfo.InvariantCulture)
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType == "float" || normalizedType == "System.Single")
        {
            return float.TryParse(literalValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var floatValue)
                ? floatValue.ToString("R", CultureInfo.InvariantCulture) + "f"
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType == "decimal" || normalizedType == "System.Decimal")
        {
            return decimal.TryParse(literalValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var decimalValue)
                ? decimalValue.ToString(CultureInfo.InvariantCulture) + "m"
                : ConvertViaTypeConverter(normalizedType, valueExpression);
        }

        if (normalizedType.EndsWith("?", StringComparison.Ordinal))
        {
            var innerType = normalizedType.Substring(0, normalizedType.Length - 1);
            if (literalValue.Equals("null", StringComparison.OrdinalIgnoreCase))
            {
                return "null";
            }

            return ConvertLiteralExpression(valueExpression, innerType);
        }

        return ConvertViaTypeConverter(normalizedType, valueExpression);
    }

    private static string ConvertViaTypeConverter(string normalizedType, string valueExpression)
    {
        var qualifiedType = QualifyType(normalizedType);
        return "(" + qualifiedType + ")global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(" +
               qualifiedType + ")).ConvertFromInvariantString(" + valueExpression + ")";
    }

    private static bool TryUnquote(string expression, out string literal)
    {
        literal = expression;
        var trimmed = expression.Trim();
        if (trimmed.Length < 2 || trimmed[0] != '"' || trimmed[trimmed.Length - 1] != '"')
        {
            return false;
        }

        var inner = trimmed.Substring(1, trimmed.Length - 2);
        literal = inner.Replace("\\\"", "\"").Replace("\\\\", "\\");
        return true;
    }

    private static string QualifyType(string? typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
        {
            return "object";
        }

        var trimmed = typeName.Trim();
        switch (trimmed)
        {
            case "bool":
            case "byte":
            case "sbyte":
            case "short":
            case "ushort":
            case "int":
            case "uint":
            case "long":
            case "ulong":
            case "float":
            case "double":
            case "decimal":
            case "char":
            case "string":
            case "object":
            case "void":
                return trimmed;
        }

        return trimmed.StartsWith("global::", StringComparison.Ordinal)
            ? trimmed
            : "global::" + trimmed;
    }

    private static string? ResolveBaseTypeName(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var rootTypeName = viewModel.RootObject.TypeName;
        if (string.IsNullOrWhiteSpace(rootTypeName))
        {
            return null;
        }

        var normalizedRoot = rootTypeName.Replace("global::", string.Empty);
        if (!string.IsNullOrWhiteSpace(doc.ClassFullName) &&
            string.Equals(normalizedRoot, doc.ClassFullName, StringComparison.Ordinal))
        {
            return null;
        }

        return QualifyType(rootTypeName);
    }

    private sealed class GraphEmitter
    {
        private readonly Dictionary<string, string> _namedFieldTypes;
        private int _localCounter;

        public GraphEmitter(ResolvedViewModel viewModel, StringBuilder builder, string memberIndent)
        {
            ViewModel = viewModel;
            Builder = builder;
            MemberIndent = memberIndent;
            _namedFieldTypes = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var namedElement in viewModel.NamedElements)
            {
                if (!_namedFieldTypes.ContainsKey(namedElement.Name))
                {
                    _namedFieldTypes[namedElement.Name] = namedElement.TypeName;
                }
            }
        }

        public ResolvedViewModel ViewModel { get; }

        public StringBuilder Builder { get; }

        public string MemberIndent { get; }

        public void EmitNodeInitialization(
            ResolvedObjectNode node,
            string instanceVariable,
            bool isRootNode,
            string? ambientStyleTargetTypeExpression)
        {
            var nextAmbientStyleTargetTypeExpression = ambientStyleTargetTypeExpression;
            if (string.Equals(node.TypeName.Replace("global::", string.Empty), "System.Windows.Style", StringComparison.Ordinal))
            {
                nextAmbientStyleTargetTypeExpression = instanceVariable + ".TargetType";
            }

            EmitNamedFieldAssignment(node, instanceVariable);
            EmitPropertyAssignments(node, instanceVariable, nextAmbientStyleTargetTypeExpression);
            EmitPropertyElementAssignments(node, instanceVariable);
            EmitEventSubscriptions(node, instanceVariable);
            EmitChildNodes(node, instanceVariable, nextAmbientStyleTargetTypeExpression);

            if (isRootNode && !string.IsNullOrWhiteSpace(node.Name))
            {
                EmitNamedFieldAssignment(node, instanceVariable);
            }
        }

        private void EmitNamedFieldAssignment(ResolvedObjectNode node, string instanceVariable)
        {
            if (string.IsNullOrWhiteSpace(node.Name) || !_namedFieldTypes.TryGetValue(node.Name, out var fieldType))
            {
                return;
            }

            Builder.AppendLine(MemberIndent + "    this." + node.Name + " = (" + QualifyType(fieldType) + ")" + instanceVariable + ";");
        }

        private void EmitPropertyAssignments(
            ResolvedObjectNode node,
            string instanceVariable,
            string? ambientStyleTargetTypeExpression)
        {
            foreach (var assignment in node.PropertyAssignments)
            {
                // StartupUri is handled by an OnStartup override (see ResolveStartupWindowType /
                // EmitOnStartup).  Setting it here would cause Application.DoStartup() to try to
                // load a BAML resource that doesn't exist in Phase 3.
                if (string.Equals(assignment.PropertyName, "StartupUri", StringComparison.Ordinal))
                    continue;

                // {Binding ...} — emit a SetBinding call instead of a direct property assignment.
                if (assignment.ValueKind == ResolvedValueKind.Binding)
                {
                    EmitSetBinding(node.TypeName, assignment, instanceVariable);
                    continue;
                }

                if (ambientStyleTargetTypeExpression is not null &&
                    string.Equals(node.TypeName.Replace("global::", string.Empty), "System.Windows.Setter", StringComparison.Ordinal) &&
                    string.Equals(assignment.PropertyName, "Property", StringComparison.Ordinal) &&
                    (string.Equals(assignment.ClrPropertyTypeName?.Replace("global::", string.Empty), "System.Windows.DependencyProperty", StringComparison.Ordinal) ||
                     string.Equals(assignment.ClrPropertyTypeName, "DependencyProperty", StringComparison.Ordinal)))
                {
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        instanceVariable + "." + assignment.PropertyName + " = " +
                        "__WXSG_ResolveSetterDependencyProperty(" + assignment.ValueExpression + ", " + ambientStyleTargetTypeExpression + ");");
                    continue;
                }

                if (string.Equals(node.TypeName.Replace("global::", string.Empty), "System.Windows.Setter", StringComparison.Ordinal) &&
                    string.Equals(assignment.PropertyName, "Value", StringComparison.Ordinal))
                {
                    var convertedSetterValue = ConvertLiteralExpression(assignment.ValueExpression, assignment.ClrPropertyTypeName);
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        instanceVariable + "." + assignment.PropertyName + " = " +
                        "__WXSG_ConvertSetterValue(" + instanceVariable + ".Property, " + convertedSetterValue + ");");
                    continue;
                }

                var convertedValue = ConvertLiteralExpression(assignment.ValueExpression, assignment.ClrPropertyTypeName);
                var frameworkOwner = assignment.GetFrameworkPropertyOwnerTypeName(WpfFrameworkId);
                if (!string.IsNullOrWhiteSpace(frameworkOwner))
                {
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        QualifyType(frameworkOwner) +
                        ".Set" + assignment.PropertyName + "(" + instanceVariable + ", " + convertedValue + ");");
                    continue;
                }

                Builder.AppendLine(
                    MemberIndent + "    " +
                    instanceVariable + "." + assignment.PropertyName + " = " + convertedValue + ";");
            }
        }

        private void EmitSetBinding(string? instanceTypeName, ResolvedPropertyAssignment assignment, string instanceVariable)
        {
            // Re-parse the raw XAML binding expression stored in ValueExpression.
            if (!MarkupParser.TryParseMarkupExtension(assignment.ValueExpression, out var info))
                return;

            // Path: first positional arg OR named "Path" arg.
            string? path = null;
            if (info.PositionalArguments.Length > 0)
                path = info.PositionalArguments[0];
            else
                info.NamedArguments.TryGetValue("Path", out path);

            var pathLiteral = string.IsNullOrEmpty(path)
                ? string.Empty
                : "\"" + path!.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

            // Build the Binding object-initializer for optional named arguments.
            var initParts = new List<string>();
            if (info.NamedArguments.TryGetValue("Mode", out var mode))
                initParts.Add("Mode = global::System.Windows.Data.BindingMode." + mode);
            if (info.NamedArguments.TryGetValue("UpdateSourceTrigger", out var ust))
                initParts.Add("UpdateSourceTrigger = global::System.Windows.Data.UpdateSourceTrigger." + ust);

            var bindingExpr = "new global::System.Windows.Data.Binding(" + pathLiteral + ")";
            if (initParts.Count > 0)
                bindingExpr += " { " + string.Join(", ", initParts) + " }";

            if (ShouldAssignBindingDirectly(instanceTypeName, assignment))
            {
                Builder.AppendLine(MemberIndent + "    " + instanceVariable +
                                   "." + assignment.PropertyName + " = " + bindingExpr + ";");
                return;
            }

            // DependencyProperty field: WPF convention is OwnerType.PropertyNameProperty.
            // For attached properties the framework owner type is stored in FrameworkPayload.
            var ownerTypeName = assignment.GetFrameworkPropertyOwnerTypeName(WpfFrameworkId)
                                ?? assignment.ClrPropertyOwnerTypeName;
            var dpField = QualifyType(ownerTypeName) + "." + assignment.PropertyName + "Property";

            Builder.AppendLine(MemberIndent + "    global::System.Windows.Data.BindingOperations.SetBinding(" +
                               instanceVariable + ", " + dpField + ", " + bindingExpr + ");");
        }

        private static bool ShouldAssignBindingDirectly(string? instanceTypeName, ResolvedPropertyAssignment assignment)
        {
            var propertyTypeName = assignment.ClrPropertyTypeName ?? string.Empty;
            var propertyName = assignment.PropertyName ?? string.Empty;
            var instanceType = instanceTypeName ?? string.Empty;

            // Non-DependencyObject-style binding sinks: assign the Binding instance directly.
            if (propertyTypeName.Contains("System.Windows.Data.BindingBase", StringComparison.Ordinal) ||
                propertyTypeName.Contains("System.Windows.Data.Binding", StringComparison.Ordinal))
            {
                return true;
            }

            if (propertyName.Equals("Binding", StringComparison.Ordinal) &&
                instanceType.EndsWith(".DataTrigger", StringComparison.Ordinal))
            {
                return true;
            }

            if (propertyName.Equals("DisplayMemberBinding", StringComparison.Ordinal))
            {
                return true;
            }

            if (propertyName.Equals("Value", StringComparison.Ordinal) &&
                instanceType.EndsWith(".Setter", StringComparison.Ordinal))
            {
                return true;
            }

            return false;
        }

        public void EmitHotReloadCollectionCleanup(ResolvedObjectNode rootNode)
        {
            var emittedMemberAccesses = new HashSet<string>(StringComparer.Ordinal);

            if (!string.IsNullOrWhiteSpace(rootNode.ContentPropertyName))
            {
                var contentPropertyName = rootNode.ContentPropertyName;
                switch (rootNode.ChildAttachmentMode)
                {
                    case ResolvedChildAttachmentMode.Content:
                        Builder.AppendLine(MemberIndent + "    this." + contentPropertyName + " = null;");
                        emittedMemberAccesses.Add("this." + contentPropertyName);
                        break;
                    case ResolvedChildAttachmentMode.ChildrenCollection:
                    case ResolvedChildAttachmentMode.ItemsCollection:
                    case ResolvedChildAttachmentMode.DirectAdd:
                    case ResolvedChildAttachmentMode.DictionaryAdd:
                        Builder.AppendLine(MemberIndent + "    __WXSG_ClearCollectionLike(this." + contentPropertyName + ");");
                        emittedMemberAccesses.Add("this." + contentPropertyName);
                        break;
                }
            }

            foreach (var propertyElement in rootNode.PropertyElementAssignments)
            {
                if (propertyElement.ObjectValues.IsDefaultOrEmpty)
                {
                    continue;
                }

                if (!string.IsNullOrWhiteSpace(propertyElement.GetFrameworkPropertyOwnerTypeName(WpfFrameworkId)))
                {
                    continue;
                }

                var forceResourcesDictionaryAdd =
                    propertyElement.PropertyName.Equals("Resources", StringComparison.Ordinal) &&
                    propertyElement.ObjectValues.Length > 0;

                if (!(propertyElement.IsCollectionAdd ||
                      IsCollectionLikeTypeName(propertyElement.ClrPropertyTypeName) ||
                      forceResourcesDictionaryAdd))
                {
                    continue;
                }

                var memberAccess = "this." + propertyElement.PropertyName;
                if (!emittedMemberAccesses.Add(memberAccess))
                {
                    continue;
                }

                Builder.AppendLine(MemberIndent + "    __WXSG_ClearCollectionLike(" + memberAccess + ");");
            }
        }

        private void EmitPropertyElementAssignments(ResolvedObjectNode node, string instanceVariable)
        {
            foreach (var propertyElement in node.PropertyElementAssignments)
            {
                if (propertyElement.ObjectValues.IsDefaultOrEmpty)
                {
                    continue;
                }

                var createdValues = new List<string>(propertyElement.ObjectValues.Length);
                foreach (var objectValue in propertyElement.ObjectValues)
                {
                    createdValues.Add(EmitChildObjectCreation(objectValue, ambientStyleTargetTypeExpression: null));
                }

                var frameworkOwner = propertyElement.GetFrameworkPropertyOwnerTypeName(WpfFrameworkId);
                if (!string.IsNullOrWhiteSpace(frameworkOwner))
                {
                    var normalizedOwner = frameworkOwner.Replace("global::", string.Empty);
                    if (normalizedOwner == "Microsoft.Xaml.Behaviors.Interaction" &&
                        (propertyElement.PropertyName.Equals("Behaviors", StringComparison.Ordinal) ||
                         propertyElement.PropertyName.Equals("Triggers", StringComparison.Ordinal)))
                    {
                        var getterName = propertyElement.PropertyName.Equals("Behaviors", StringComparison.Ordinal)
                            ? "GetBehaviors"
                            : "GetTriggers";
                        foreach (var childVariable in createdValues)
                        {
                            Builder.AppendLine(
                                MemberIndent + "    " +
                                QualifyType(frameworkOwner) + "." + getterName + "(" + instanceVariable + ").Add(" + childVariable + ");");
                        }

                        continue;
                    }

                    foreach (var childVariable in createdValues)
                    {
                        Builder.AppendLine(
                            MemberIndent + "    " +
                            QualifyType(frameworkOwner) +
                            ".Set" + propertyElement.PropertyName + "(" + instanceVariable + ", " + childVariable + ");");
                    }

                    continue;
                }

                // WPF template visual trees require FrameworkElementFactory construction.
                // Until WXSG emits template factories, skip direct object assignment to VisualTree.
                if (propertyElement.PropertyName.Equals("VisualTree", StringComparison.Ordinal))
                {
                    continue;
                }

                var forceResourcesDictionaryAdd =
                    propertyElement.PropertyName.Equals("Resources", StringComparison.Ordinal) &&
                    propertyElement.ObjectValues.Length > 0;

                if (propertyElement.IsCollectionAdd ||
                    IsCollectionLikeTypeName(propertyElement.ClrPropertyTypeName) ||
                    forceResourcesDictionaryAdd)
                {
                    var isDictionaryAdd = forceResourcesDictionaryAdd ||
                                          IsDictionaryLikeTypeName(propertyElement.ClrPropertyTypeName);
                    for (var index = 0; index < createdValues.Count; index++)
                    {
                        var childVariable = createdValues[index];
                        if (isDictionaryAdd)
                        {
                            var keyExpression = BuildDictionaryKeyExpression(
                                propertyElement.PropertyName,
                                propertyElement.ObjectValues[index],
                                childVariable);
                            Builder.AppendLine(
                                MemberIndent + "    " +
                                instanceVariable + "." + propertyElement.PropertyName + ".Add(" +
                                keyExpression + ", " + childVariable + ");");
                        }
                        else
                        {
                            Builder.AppendLine(
                                MemberIndent + "    " +
                                instanceVariable + "." + propertyElement.PropertyName + ".Add(" + childVariable + ");");
                        }
                    }

                    continue;
                }

                Builder.AppendLine(
                    MemberIndent + "    " +
                    instanceVariable + "." + propertyElement.PropertyName + " = " + createdValues[0] + ";");
            }
        }

        private void EmitEventSubscriptions(ResolvedObjectNode node, string instanceVariable)
        {
            foreach (var subscription in node.EventSubscriptions)
            {
                if (string.IsNullOrWhiteSpace(subscription.HandlerMethodName))
                {
                    continue;
                }

                if (subscription.Kind == ResolvedEventSubscriptionKind.RoutedEvent &&
                    !string.IsNullOrWhiteSpace(subscription.RoutedEventOwnerTypeName) &&
                    !string.IsNullOrWhiteSpace(subscription.RoutedEventFieldName))
                {
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        instanceVariable +
                        ".AddHandler(" +
                        QualifyType(subscription.RoutedEventOwnerTypeName) +
                        "." + subscription.RoutedEventFieldName +
                        ", new global::System.Windows.RoutedEventHandler(this." +
                        subscription.HandlerMethodName + "));" );
                    continue;
                }

                Builder.AppendLine(
                    MemberIndent + "    " +
                    instanceVariable +
                    "." + subscription.EventName +
                    " += this." + subscription.HandlerMethodName + ";");
            }
        }

        private void EmitChildNodes(
            ResolvedObjectNode node,
            string instanceVariable,
            string? ambientStyleTargetTypeExpression)
        {
            if (node.Children.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (var child in node.Children)
            {
                var childVariable = EmitChildObjectCreation(child, ambientStyleTargetTypeExpression);
                AttachChild(node, instanceVariable, child, childVariable);
            }
        }

        private string EmitChildObjectCreation(ResolvedObjectNode child, string? ambientStyleTargetTypeExpression)
        {
            var localVariable = "__node" + _localCounter.ToString(CultureInfo.InvariantCulture);
            _localCounter++;

            var creationExpression = !string.IsNullOrWhiteSpace(child.FactoryExpression)
                ? child.FactoryExpression
                : "new " + QualifyType(child.TypeName) + "()";

            Builder.AppendLine(MemberIndent + "    var " + localVariable + " = " + creationExpression + ";");
            EmitNodeInitialization(child, localVariable, isRootNode: false, ambientStyleTargetTypeExpression);
            return localVariable;
        }

        private void AttachChild(
            ResolvedObjectNode parent,
            string parentVariable,
            ResolvedObjectNode child,
            string childVariable)
        {
            var contentProperty = parent.ContentPropertyName;
            if (string.IsNullOrWhiteSpace(contentProperty))
            {
                return;
            }

            if (contentProperty.Equals("VisualTree", StringComparison.Ordinal))
            {
                return;
            }

            switch (parent.ChildAttachmentMode)
            {
                case ResolvedChildAttachmentMode.Content:
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        parentVariable + "." + contentProperty + " = " + childVariable + ";");
                    return;
                case ResolvedChildAttachmentMode.ChildrenCollection:
                case ResolvedChildAttachmentMode.ItemsCollection:
                case ResolvedChildAttachmentMode.DirectAdd:
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        parentVariable + "." + contentProperty + ".Add(" + childVariable + ");");
                    return;
                case ResolvedChildAttachmentMode.DictionaryAdd:
                    var keyExpression = BuildDictionaryKeyExpression(contentProperty, child, childVariable);
                    Builder.AppendLine(
                        MemberIndent + "    " +
                        parentVariable + "." + contentProperty + ".Add(" + keyExpression + ", " + childVariable + ");");
                    return;
                default:
                    return;
            }
        }

        private static string BuildDictionaryKeyExpression(
            string? parentPropertyName,
            ResolvedObjectNode child,
            string childVariable)
        {
            if (!string.IsNullOrWhiteSpace(child.KeyExpression))
            {
                return child.KeyExpression;
            }

            if (string.Equals(parentPropertyName, "Resources", StringComparison.Ordinal) &&
                string.Equals(child.TypeName.Replace("global::", string.Empty), "System.Windows.Style", StringComparison.Ordinal))
            {
                return childVariable + ".TargetType";
            }

            return AsFallbackDictionaryKey(child);
        }

        private static bool IsCollectionLikeTypeName(string? typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
            {
                return false;
            }

            var normalized = typeName.Replace("global::", string.Empty);
            return normalized.Contains("ICollection", StringComparison.Ordinal) ||
                   normalized.Contains("IList", StringComparison.Ordinal) ||
                   normalized.Contains("IEnumerable", StringComparison.Ordinal) ||
                   normalized.Contains("Collection", StringComparison.Ordinal) ||
                   normalized.Contains("List", StringComparison.Ordinal);
        }

        private static bool IsDictionaryLikeTypeName(string? typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
            {
                return false;
            }

            var normalized = typeName.Replace("global::", string.Empty);
            return normalized.Contains("IDictionary", StringComparison.Ordinal) ||
                   normalized.Contains("Dictionary", StringComparison.Ordinal);
        }

        private static string AsFallbackDictionaryKey(ResolvedObjectNode child)
        {
            if (!string.IsNullOrWhiteSpace(child.Name))
            {
                return "\"" + child.Name + "\"";
            }

            return "\"" + child.TypeName.Replace("\"", "\\\"") + "\"";
        }
    }
}
