using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using XamlToCSharpGenerator.Core.Abstractions;
using XamlToCSharpGenerator.Core.Models;

namespace XamlToCSharpGenerator.WPF.Emission;

/// <summary>
/// VB.NET emitter for WPF XAML source generation.
///
/// This emitter intentionally uses a BAML-backed InitializeComponent() path:
/// - WPF markup compilation still produces BAML resources.
/// - Generated VB code loads BAML via Application.LoadComponent.
/// - x:Name fields are wired via FindName.
///
/// This keeps WXSG usable for VB projects without requiring full VB object-graph
/// emission parity with the C# Phase-3 emitter.
/// </summary>
public sealed class WpfVisualBasicCodeEmitter : IXamlCodeEmitter
{
    private const string GeneratorVersion = "0.3.0-vb";
    private const string GeneratorName = "XamlToCSharpGenerator.Generator.WPF";
    private static readonly HashSet<string> VisualBasicKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        "AddHandler", "AddressOf", "Alias", "And", "AndAlso", "As", "Boolean", "ByRef",
        "Byte", "ByVal", "Call", "Case", "Catch", "CBool", "CByte", "CChar", "CDate",
        "CDbl", "CDec", "Char", "CInt", "Class", "CLng", "CObj", "Const", "Continue",
        "CSByte", "CShort", "CSng", "CStr", "CType", "CUInt", "CULng", "CUShort", "Date",
        "Decimal", "Declare", "Default", "Delegate", "Dim", "DirectCast", "Do", "Double",
        "Each", "Else", "ElseIf", "End", "EndIf", "Enum", "Erase", "Error", "Event",
        "Exit", "False", "Finally", "For", "Friend", "Function", "Get", "GetType", "Global",
        "GoSub", "GoTo", "Handles", "If", "Implements", "Imports", "In", "Inherits",
        "Integer", "Interface", "Is", "IsNot", "Let", "Lib", "Like", "Long", "Loop",
        "Me", "Mod", "Module", "MustInherit", "MustOverride", "MyBase", "MyClass",
        "Namespace", "Narrowing", "New", "Next", "Not", "Nothing", "NotInheritable",
        "NotOverridable", "Object", "Of", "On", "Operator", "Option", "Optional", "Or",
        "OrElse", "Overloads", "Overridable", "Overrides", "ParamArray", "Partial",
        "Private", "Property", "Protected", "Public", "RaiseEvent", "ReadOnly", "ReDim",
        "REM", "RemoveHandler", "Resume", "Return", "SByte", "Select", "Set", "Shadows",
        "Shared", "Short", "Single", "Static", "Step", "Stop", "String", "Structure",
        "Sub", "SyncLock", "Then", "Throw", "To", "True", "Try", "TryCast", "TypeOf",
        "UInteger", "ULong", "UShort", "Using", "Variant", "Wend", "When", "While",
        "Widening", "With", "WithEvents", "WriteOnly", "Xor"
    };

    public (string HintName, string Source) Emit(ResolvedViewModel viewModel)
    {
        var doc = viewModel.Document;
        if (doc.ClassFullName is null)
        {
            return (string.Empty, string.Empty);
        }

        var source = BuildSource(viewModel, doc);
        var hintName = doc.ClassFullName.Replace('.', '_').Replace('+', '_') + ".wpf.g.vb";
        return (hintName, source);
    }

    private static string BuildSource(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var sb = new StringBuilder(1024);
        var classNamespace = doc.ClassNamespace;
        var className = doc.ClassName;
        var hasNamespace = !string.IsNullOrWhiteSpace(classNamespace);
        var classModifier = NormalizeClassModifier(viewModel.ClassModifier);
        var baseTypeName = NormalizeTypeName(viewModel.RootObject.TypeName);

        sb.AppendLine("' <auto-generated/>");
        sb.AppendLine("' Generated by " + GeneratorName + " " + GeneratorVersion);
        sb.AppendLine("Option Strict Off");
        sb.AppendLine("Option Explicit On");
        sb.AppendLine();

        if (hasNamespace)
        {
            sb.AppendLine("Namespace " + classNamespace);
            sb.AppendLine();
        }

        var i0 = hasNamespace ? "    " : string.Empty;
        var i1 = i0 + "    ";

        sb.Append(i0);
        sb.Append(classModifier);
        sb.Append(" Partial Class ");
        sb.Append(className);
        if (!string.IsNullOrWhiteSpace(baseTypeName))
        {
            sb.AppendLine();
            sb.Append(i1);
            sb.Append("Inherits ");
            sb.Append(baseTypeName);
        }
        sb.AppendLine();

        foreach (var element in viewModel.NamedElements)
        {
            sb.Append(i1);
            sb.Append("Private ");
            sb.Append(EscapeIdentifier(element.Name));
            sb.Append(" As ");
            sb.AppendLine(NormalizeTypeName(element.TypeName));
        }

        if (viewModel.NamedElements.Length > 0)
        {
            sb.AppendLine();
        }

        sb.AppendLine(i1 + "Private _contentLoaded As Boolean");
        sb.AppendLine();
        sb.AppendLine(i1 + "Public Sub InitializeComponent()");
        sb.AppendLine(i1 + "    If _contentLoaded Then");
        sb.AppendLine(i1 + "        Return");
        sb.AppendLine(i1 + "    End If");
        sb.AppendLine();
        sb.AppendLine(i1 + "    _contentLoaded = True");
        sb.AppendLine(i1 + "    System.Windows.Application.LoadComponent(Me, New System.Uri(\"" + EscapeVisualBasicStringLiteral(viewModel.BuildUri) + "\", System.UriKind.RelativeOrAbsolute))");

        foreach (var element in viewModel.NamedElements)
        {
            sb.Append(i1);
            sb.Append("    Me.");
            sb.Append(EscapeIdentifier(element.Name));
            sb.Append(" = CType(Me.FindName(\"");
            sb.Append(EscapeVisualBasicStringLiteral(element.Name));
            sb.Append("\"), ");
            sb.Append(NormalizeTypeName(element.TypeName));
            sb.AppendLine(")");
        }

        sb.AppendLine(i1 + "End Sub");

        if (IsApplicationDefinition(viewModel))
        {
            sb.AppendLine();
            sb.AppendLine(i1 + "<System.STAThread>");
            sb.AppendLine(i1 + "Public Shared Sub Main()");
            sb.AppendLine(i1 + "    Dim app As New " + className + "()");
            sb.AppendLine(i1 + "    app.InitializeComponent()");
            sb.AppendLine(i1 + "    app.Run()");
            sb.AppendLine(i1 + "End Sub");
        }

        sb.AppendLine(i0 + "End Class");

        if (hasNamespace)
        {
            sb.AppendLine();
            sb.AppendLine("End Namespace");
        }

        return sb.ToString();
    }

    private static string NormalizeClassModifier(string? modifier)
    {
        if (string.IsNullOrWhiteSpace(modifier))
        {
            return "Public";
        }

        return string.Equals(modifier.Trim(), "internal", StringComparison.OrdinalIgnoreCase)
            ? "Friend"
            : "Public";
    }

    private static string NormalizeTypeName(string? typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
        {
            return "Object";
        }

        return typeName.Replace("global::", string.Empty);
    }

    private static bool IsApplicationDefinition(ResolvedViewModel viewModel)
    {
        var rootType = NormalizeTypeName(viewModel.RootObject.TypeName);
        return string.Equals(rootType, "System.Windows.Application", StringComparison.Ordinal) ||
               string.Equals(rootType, "Application", StringComparison.Ordinal);
    }

    private static string EscapeVisualBasicStringLiteral(string value)
    {
        return value.Replace("\"", "\"\"");
    }

    private static string EscapeIdentifier(string identifier)
    {
        return VisualBasicKeywords.Contains(identifier) ? "[" + identifier + "]" : identifier;
    }
}
