name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Triggers on any tag push starting with 'v'

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Solution
        run: dotnet build src/wxsg.slnx --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --no-restore src\XamlToCSharpGenerator.Generator.WPF\XamlToCSharpGenerator.Generator.WPF.csproj -o out /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Push to GitHub Packages
        run: Get-ChildItem "out/*.nupkg" | ForEach-Object { dotnet nuget push $_.FullName --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate }
