name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Triggers on any tag push starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Specify your .NET version
          # This automatically creates a nuget.config with the GitHub source
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Solution
        run: dotnet build src/wxsg.slnx --configuration Release

      - name: Pack
        # --no-restore ensures we use the authenticated restore from the previous step
        run: dotnet pack --configuration Release --no-restore src\XamlToCSharpGenerator.Generator.WPF\XamlToCSharpGenerator.Generator.WPF.csproj -o out

      - name: Push to GitHub Packages
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
