using System;
using System.Collections.Generic;
using System.IO;
using System.Resources;
using System.Threading;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using LeXtudio.Metadata.Mutable;

namespace XamlToCSharpGenerator.Build.Tasks
{
    /// <summary>
    /// MSBuild task that injects BAML entries generated by MarkupCompilePass2 into the
    /// compiled assembly's .g.resources manifest resource, enabling WPF to load
    /// deferred classless XAML (ResourceDictionaries with local type references) via
    /// the normal BAML path rather than raw XAML at runtime.
    /// </summary>
    public class WxsgInjectBamlTask : Task
    {
        /// <summary>Path to the compiled assembly (.dll/.exe) to modify.</summary>
        [Required]
        public string AssemblyPath { get; set; } = string.Empty;

        /// <summary>
        /// BAML files generated by MarkupCompilePass2.
        /// Each item's ItemSpec is the full path to the .baml file.
        /// The metadata key "ResourceKey" (if present) overrides the default key
        /// derivation (lowercase relative path with forward slashes).
        /// </summary>
        [Required]
        public ITaskItem[] BamlFiles { get; set; } = Array.Empty<ITaskItem>();

        /// <summary>Assembly name used to locate the .g.resources manifest resource.</summary>
        [Required]
        public string AssemblyName { get; set; } = string.Empty;

        /// <summary>
        /// Root directory used to compute relative paths for resource keys.
        /// Typically the project directory or IntermediateOutputPath.
        /// </summary>
        [Required]
        public string ProjectDirectory { get; set; } = string.Empty;

        public override bool Execute()
        {
            if (!File.Exists(AssemblyPath))
            {
                Log.LogError("WxsgInjectBaml: assembly not found: {0}", AssemblyPath);
                return false;
            }

            if (BamlFiles.Length == 0)
            {
                Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: no BAML files to inject, skipping.");
                return true;
            }

            try
            {
                var resourceName = AssemblyName.ToLowerInvariant() + ".g.resources";
                Log.LogMessage(MessageImportance.Normal,
                    "WxsgInjectBaml: injecting {0} BAML file(s) into '{1}' in '{2}'",
                    BamlFiles.Length, resourceName, Path.GetFileName(AssemblyPath));

                // Read the assembly bytes into memory first so the file is not held open
                // (PEReader keeps the stream open; we need to overwrite the file later)
                var assemblyBytes = File.ReadAllBytes(AssemblyPath);

                // Diagnostic snapshot: write pre-modification copy to temp for inspection
                try
                {
                    var prePath = Path.Combine(Path.GetTempPath(), Path.GetFileName(AssemblyPath) + ".wxsg.pre");
                    File.WriteAllBytes(prePath, assemblyBytes);
                    Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: wrote pre-snapshot to '{0}'", prePath);
                }
                catch (Exception ex)
                {
                    Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: failed to write pre-snapshot: {0}", ex.Message);
                }
                var reader = new MutableAssemblyReader();
                var assembly = reader.Read(new MemoryStream(assemblyBytes), new MutableReaderParameters { ReadMethodBodies = true });
                assembly.MainModule.FileName = AssemblyPath;
                var module = assembly.MainModule;
                if (reader is IDisposable readerDisposable)
                {
                    readerDisposable.Dispose();
                }

                // Find the .g.resources embedded resource
                MutableEmbeddedResource? gResources = null;
                foreach (var res in module.Resources)
                {
                    if (res is MutableEmbeddedResource embedded &&
                        string.Equals(embedded.Name, resourceName, StringComparison.OrdinalIgnoreCase))
                    {
                        gResources = embedded;
                        break;
                    }
                }

                if (gResources == null)
                {
                    Log.LogError("WxsgInjectBaml: could not find manifest resource '{0}' in '{1}'",
                        resourceName, AssemblyPath);
                    return false;
                }

                // Parse existing .g.resources entries and preserve their type names
                var entries = new Dictionary<string, (string TypeName, byte[] Data)>(StringComparer.OrdinalIgnoreCase);
                var existingData = gResources.GetResourceData();
                try
                {
                    using (var ms = new MemoryStream(existingData))
                    using (var resourceReader = new ResourceReader(ms))
                    {
                        var enumerator = resourceReader.GetEnumerator();
                        while (enumerator.MoveNext())
                        {
                            var key = enumerator.Key?.ToString() ?? string.Empty;
                            resourceReader.GetResourceData(key, out var typeName, out var value);
                            entries[key] = (typeName ?? string.Empty, value);
                            Log.LogMessage(MessageImportance.Low,
                                "WxsgInjectBaml: existing resource key: '{0}' type: '{1}' ({2} bytes)", key, typeName, value.Length);
                        }
                    }

                    // Diagnostic: write pre .g.resources snapshot
                    try
                    {
                        var preGResPath = Path.Combine(Path.GetTempPath(), Path.GetFileName(AssemblyPath) + ".g.resources.pre");
                        File.WriteAllBytes(preGResPath, existingData);
                        Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: wrote pre .g.resources snapshot to '{0}'", preGResPath);
                    }
                    catch (Exception ex)
                    {
                        Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: failed to write pre .g.resources snapshot: {0}", ex.Message);
                    }
                }
                catch (Exception ex)
                {
                    Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: failed to read existing .g.resources: {0}", ex.Message);
                    throw;
                }

                // Add/replace BAML entries
                var projectDir = Path.GetFullPath(ProjectDirectory);
                foreach (var item in BamlFiles)
                {
                    var bamlPath = item.GetMetadata("FullPath");
                    if (string.IsNullOrEmpty(bamlPath))
                        bamlPath = Path.GetFullPath(item.ItemSpec);

                    if (!File.Exists(bamlPath))
                    {
                        Log.LogWarning("WxsgInjectBaml: BAML file not found, skipping: {0}", bamlPath);
                        continue;
                    }

                    // Determine the resource key. By convention WPF uses:
                    // lowercase relative path with forward slashes, e.g.
                    // "controls/treeview/sharptreeview.baml"
                    var resourceKey = item.GetMetadata("ResourceKey");
                    if (string.IsNullOrEmpty(resourceKey))
                    {
                        // Derive from the BAML file path relative to the project dir
                        var rel = MakeRelativePath(projectDir, bamlPath)
                            .Replace('\\', '/')
                            .ToLowerInvariant();
                        // Remove leading "./" if present
                        if (rel.StartsWith("./", StringComparison.Ordinal))
                            rel = rel.Substring(2);
                        resourceKey = rel;
                    }

                    var bamlBytes = File.ReadAllBytes(bamlPath);
                    const string streamTypeName = "ResourceTypeCode.Stream";
                    entries[resourceKey] = (streamTypeName, CreateStreamResourceData(bamlBytes));
                    Log.LogMessage(MessageImportance.Normal,
                        "WxsgInjectBaml: adding BAML key '{0}' type '{1}' ({2} bytes)", resourceKey, streamTypeName, bamlBytes.Length);
                }

                // Serialize updated resource set (use preserved type names)
                byte[] updatedData;
                using (var ms = new MemoryStream())
                {
                    using (var writer = new ResourceWriter(ms))
                    {
                        foreach (var kvp in entries)
                            writer.AddResourceData(kvp.Key, kvp.Value.TypeName, kvp.Value.Data);
                    }
                    updatedData = ms.ToArray();
                }

                // Diagnostic: write post .g.resources snapshot
                try
                {
                    var postGResPath = Path.Combine(Path.GetTempPath(), Path.GetFileName(AssemblyPath) + ".g.resources.post");
                    File.WriteAllBytes(postGResPath, updatedData);
                    Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: wrote post .g.resources snapshot to '{0}'", postGResPath);
                }
                catch (Exception ex)
                {
                    Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: failed to write post .g.resources snapshot: {0}", ex.Message);
                }

                // Replace the resource data in the module
                gResources.SetResourceData(updatedData);

                // Rewrite to a temp file in %TEMP% to avoid any directory-permission issues,
                // then copy back over the original assembly.
                var tempPath = Path.Combine(Path.GetTempPath(), Path.GetFileNameWithoutExtension(AssemblyPath) + ".wxsg.tmp");
                try
                {
                    Log.LogMessage(MessageImportance.Normal, "WxsgInjectBaml: module.Attributes={0}", assembly.MainModule.Attributes);
                    MutableAssemblyWriter writer2 = null;
                    try
                    {
                        writer2 = new MutableAssemblyWriter(assembly);
                        writer2.Write(tempPath);
                    }
                    finally
                    {
                        if (writer2 is IDisposable w) w.Dispose();
                    }

                    // Diagnostic snapshot: copy the temp output for inspection before overwriting
                    try
                    {
                        var postPath = Path.Combine(Path.GetTempPath(), Path.GetFileName(AssemblyPath) + ".wxsg.post");
                        File.Copy(tempPath, postPath, overwrite: true);
                        Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: wrote post-snapshot to '{0}'", postPath);
                    }
                    catch (Exception ex)
                    {
                        Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: failed to write post-snapshot: {0}", ex.Message);
                    }

                    // Overwrite the original assembly (retry to avoid transient file-locks)
                    const int MaxAttempts = 5;
                    var copied = false;
                    for (var attempt = 1; attempt <= MaxAttempts; attempt++)
                    {
                        try
                        {
                            File.Copy(tempPath, AssemblyPath, overwrite: true);
                            copied = true;
                            break;
                        }
                        catch (IOException) when (attempt < MaxAttempts)
                        {
                            Thread.Sleep(200);
                        }
                        catch (UnauthorizedAccessException) when (attempt < MaxAttempts)
                        {
                            Thread.Sleep(200);
                        }
                    }
                    if (!copied)
                    {
                        // Final attempt to throw the actual exception if any
                        File.Copy(tempPath, AssemblyPath, overwrite: true);
                    }
                }
                finally
                {
                    if (File.Exists(tempPath))
                        File.Delete(tempPath);
                }

                Log.LogMessage(MessageImportance.Normal,
                    "WxsgInjectBaml: assembly rewritten successfully with {0} BAML entries injected.",
                    BamlFiles.Length);
                return true;
            }
            catch (Exception ex)
            {
                Log.LogError("WxsgInjectBaml: failed: {0}", ex.ToString());
                return false;
            }
        }

        private static byte[] CreateStreamResourceData(byte[] bytes)
        {
            using var ms = new MemoryStream();
            using (var writer = new BinaryWriter(ms))
            {
                writer.Write(bytes.Length);
                writer.Write(bytes);
            }

            return ms.ToArray();
        }

        private static string MakeRelativePath(string baseDirectory, string path)
        {
            var fullBaseDirectory = EnsureTrailingDirectorySeparator(Path.GetFullPath(baseDirectory));
            var fullPath = Path.GetFullPath(path);

            var baseUri = new Uri(fullBaseDirectory, UriKind.Absolute);
            var pathUri = new Uri(fullPath, UriKind.Absolute);
            if (baseUri.Scheme != pathUri.Scheme)
                return fullPath;

            var relativeUri = baseUri.MakeRelativeUri(pathUri);
            return Uri.UnescapeDataString(relativeUri.ToString()).Replace('/', Path.DirectorySeparatorChar);
        }

        private static string EnsureTrailingDirectorySeparator(string path)
        {
            if (string.IsNullOrEmpty(path))
                return Path.DirectorySeparatorChar.ToString();

            var last = path[path.Length - 1];
            if (last == Path.DirectorySeparatorChar || last == Path.AltDirectorySeparatorChar)
                return path;

            return path + Path.DirectorySeparatorChar;
        }
    }
}
