using System;
using System.Collections.Generic;
using System.IO;
using System.Resources;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Obfuscar.Metadata.Mutable;

namespace XamlToCSharpGenerator.Build.Tasks
{
    /// <summary>
    /// MSBuild task that injects BAML entries generated by MarkupCompilePass2 into the
    /// compiled assembly's .g.resources manifest resource, enabling WPF to load
    /// deferred classless XAML (ResourceDictionaries with local type references) via
    /// the normal BAML path rather than raw XAML at runtime.
    /// </summary>
    public class WxsgInjectBamlTask : Task
    {
        /// <summary>Path to the compiled assembly (.dll/.exe) to modify.</summary>
        [Required]
        public string AssemblyPath { get; set; } = string.Empty;

        /// <summary>
        /// BAML files generated by MarkupCompilePass2.
        /// Each item's ItemSpec is the full path to the .baml file.
        /// The metadata key "ResourceKey" (if present) overrides the default key
        /// derivation (lowercase relative path with forward slashes).
        /// </summary>
        [Required]
        public ITaskItem[] BamlFiles { get; set; } = Array.Empty<ITaskItem>();

        /// <summary>Assembly name used to locate the .g.resources manifest resource.</summary>
        [Required]
        public string AssemblyName { get; set; } = string.Empty;

        /// <summary>
        /// Root directory used to compute relative paths for resource keys.
        /// Typically the project directory or IntermediateOutputPath.
        /// </summary>
        [Required]
        public string ProjectDirectory { get; set; } = string.Empty;

        public override bool Execute()
        {
            if (!File.Exists(AssemblyPath))
            {
                Log.LogError("WxsgInjectBaml: assembly not found: {0}", AssemblyPath);
                return false;
            }

            if (BamlFiles.Length == 0)
            {
                Log.LogMessage(MessageImportance.Low, "WxsgInjectBaml: no BAML files to inject, skipping.");
                return true;
            }

            try
            {
                var resourceName = AssemblyName.ToLowerInvariant() + ".g.resources";
                Log.LogMessage(MessageImportance.Normal,
                    "WxsgInjectBaml: injecting {0} BAML file(s) into '{1}' in '{2}'",
                    BamlFiles.Length, resourceName, Path.GetFileName(AssemblyPath));

                // Read the assembly bytes into memory first so the file is not held open
                // (PEReader keeps the stream open; we need to overwrite the file later)
                var assemblyBytes = File.ReadAllBytes(AssemblyPath);
                var reader = new MutableAssemblyReader();
                var assembly = reader.Read(new MemoryStream(assemblyBytes), new MutableReaderParameters { ReadMethodBodies = true });
                assembly.MainModule.FileName = AssemblyPath;
                var module = assembly.MainModule;

                // Find the .g.resources embedded resource
                MutableEmbeddedResource? gResources = null;
                foreach (var res in module.Resources)
                {
                    if (res is MutableEmbeddedResource embedded &&
                        string.Equals(embedded.Name, resourceName, StringComparison.OrdinalIgnoreCase))
                    {
                        gResources = embedded;
                        break;
                    }
                }

                if (gResources == null)
                {
                    Log.LogError("WxsgInjectBaml: could not find manifest resource '{0}' in '{1}'",
                        resourceName, AssemblyPath);
                    return false;
                }

                // Parse existing .g.resources entries
                var entries = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
                var existingData = gResources.GetResourceData();
                using (var ms = new MemoryStream(existingData))
                using (var resourceReader = new ResourceReader(ms))
                {
                    var enumerator = resourceReader.GetEnumerator();
                    while (enumerator.MoveNext())
                    {
                        var key = enumerator.Key?.ToString() ?? string.Empty;
                        resourceReader.GetResourceData(key, out _, out var value);
                        entries[key] = value;
                        Log.LogMessage(MessageImportance.Low,
                            "WxsgInjectBaml: existing resource key: '{0}' ({1} bytes)", key, value.Length);
                    }
                }

                // Add/replace BAML entries
                var projectDir = Path.GetFullPath(ProjectDirectory);
                foreach (var item in BamlFiles)
                {
                    var bamlPath = item.GetMetadata("FullPath");
                    if (string.IsNullOrEmpty(bamlPath))
                        bamlPath = Path.GetFullPath(item.ItemSpec);

                    if (!File.Exists(bamlPath))
                    {
                        Log.LogWarning("WxsgInjectBaml: BAML file not found, skipping: {0}", bamlPath);
                        continue;
                    }

                    // Determine the resource key. By convention WPF uses:
                    // lowercase relative path with forward slashes, e.g.
                    // "controls/treeview/sharptreeview.baml"
                    var resourceKey = item.GetMetadata("ResourceKey");
                    if (string.IsNullOrEmpty(resourceKey))
                    {
                        // Derive from the BAML file path relative to the project dir
                        var rel = Path.GetRelativePath(projectDir, bamlPath)
                                      .Replace('\\', '/')
                                      .ToLowerInvariant();
                        // Remove leading "./" if present
                        if (rel.StartsWith("./", StringComparison.Ordinal))
                            rel = rel.Substring(2);
                        resourceKey = rel;
                    }

                    var bamlBytes = File.ReadAllBytes(bamlPath);
                    entries[resourceKey] = bamlBytes;
                    Log.LogMessage(MessageImportance.Normal,
                        "WxsgInjectBaml: adding BAML key '{0}' ({1} bytes)", resourceKey, bamlBytes.Length);
                }

                // Serialize updated resource set
                byte[] updatedData;
                using (var ms = new MemoryStream())
                {
                    using (var writer = new ResourceWriter(ms))
                    {
                        foreach (var kvp in entries)
                            writer.AddResourceData(kvp.Key, "ResourceTypeCode.Stream", kvp.Value);
                    }
                    updatedData = ms.ToArray();
                }

                // Replace the resource data in the module
                gResources.SetResourceData(updatedData);

                // Rewrite to a temp file in %TEMP% to avoid any directory-permission issues,
                // then copy back over the original assembly.
                var tempPath = Path.Combine(Path.GetTempPath(), Path.GetFileNameWithoutExtension(AssemblyPath) + ".wxsg.tmp");
                try
                {
                    var writer2 = new MutableAssemblyWriter(assembly);
                    writer2.Write(tempPath);

                    // Overwrite the original assembly
                    File.Copy(tempPath, AssemblyPath, overwrite: true);
                }
                finally
                {
                    if (File.Exists(tempPath))
                        File.Delete(tempPath);
                }

                Log.LogMessage(MessageImportance.Normal,
                    "WxsgInjectBaml: assembly rewritten successfully with {0} BAML entries injected.",
                    BamlFiles.Length);
                return true;
            }
            catch (Exception ex)
            {
                Log.LogError("WxsgInjectBaml: failed: {0}", ex.ToString());
                return false;
            }
        }
    }
}
